// library/src/scripts/react/Button.tsx
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import * as React from 'react';
import UIIcon from 'scripts/react/Icon';
import buildClass from 'scripts/helpers/buildClass';

const JSXUIIcon = UIIcon as JSXElement;

/**
 * Button.
 */
function UIButton(props: UIButtonProps): JSX.Element {
  const { id, onClick, onFocus } = props;
  const { label, icon, iconPosition = 'left' } = props;
  const { type = 'button', modifiers = '', disabled = false } = props;
  const iconModifier = (icon !== undefined && label === undefined) ? ' icon' : '';
  const className = buildClass('ui-button', `${modifiers}${iconModifier}${disabled ? ' disabled' : ''}`);

  // -----------------------------------------------------------------------------------------------
  // CALLBACKS DECLARATION.
  // -----------------------------------------------------------------------------------------------

  const handleFocus = (event: React.FocusEvent<HTMLButtonElement>): void => {
    if (onFocus !== undefined && !disabled) {
      onFocus(event as unknown as FocusEvent);
    }
  };

  const handleClick = (event: React.MouseEvent<HTMLButtonElement>): void => {
    if (onClick !== undefined && !disabled) {
      onClick(event as unknown as MouseEvent);
    }
  };

  // -----------------------------------------------------------------------------------------------
  // COMPONENT RENDERING.
  // -----------------------------------------------------------------------------------------------

  const children = [
    (icon !== undefined) ? <JSXUIIcon key="icon" name={icon} /> : null,
    (label !== undefined) ? <span key="label" className="ui-button__label">{label}</span> : null,
  ];

  return (
    <button
      id={id}
      onFocus={handleFocus}
      onClick={handleClick}
      tabIndex={disabled ? -1 : 0}
      type={(type === 'submit') ? 'submit' : 'button'}
      className={className}
    >
      {(iconPosition === 'left') ? children : children.reverse()}
    </button>
  );
}

export default React.memo(UIButton);

// library/src/scripts/svelte/Button.svelte
<!-- Button. -->
<script lang="ts">
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import UIIcon from 'scripts/svelte/Icon.svelte';
import buildClass from 'scripts/helpers/buildClass';

export let modifiers = '';
export let id: string | undefined = undefined;
export let icon: string | undefined = undefined;
export let label: string | undefined = undefined;
export let type: 'button' | 'submit' = 'button';
export let disabled: boolean | undefined = false;
export let iconPosition: 'left' | 'right' = 'left';
export let onClick: ((event: MouseEvent) => void) | undefined = undefined;
export let onFocus: ((event: FocusEvent) => void) | undefined = undefined;

$: iconModifier = icon !== undefined && label === undefined ? ' icon' : '';
$: className = buildClass('ui-button', `${modifiers}${iconModifier}${disabled ? ' disabled' : ''}`);

// -----------------------------------------------------------------------------------------------
// CALLBACKS DECLARATION.
// -----------------------------------------------------------------------------------------------

const handleFocus = (event: FocusEvent): void => {
  if (onFocus !== undefined && !disabled) {
    onFocus(event);
  }
};

const handleClick = (event: MouseEvent): void => {
  if (onClick !== undefined && !disabled) {
    onClick(event);
  }
};
</script>

<button
  {id}
  {type}
  class={className}
  on:click={handleClick}
  on:focus={handleFocus}
  tabIndex={disabled ? -1 : 0}
>
  {#if icon !== undefined && iconPosition === 'left'}
    <UIIcon name={icon} />
  {/if}
  {#if label !== undefined}
    <span class="ui-button__label">{label}</span>
  {/if}
  {#if icon !== undefined && iconPosition === 'right'}
    <UIIcon name={icon} />
  {/if}
</button>
