// library/src/scripts/vue/FilePicker.vue
<!-- File picker. -->
<script lang="ts" setup>
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import UIIcon from 'scripts/vue/Icon.vue';
import { ref, computed, watch } from 'vue';
import markdown from 'scripts/helpers/markdown';
import buildClass from 'scripts/helpers/buildClass';
import generateRandomId from 'scripts/helpers/generateRandomId';

const emit = defineEmits({
  focus: null,
  blur: null,
  change: null,
});

const props = defineProps<{
  id?: string;
  name: string;
  icon?: string;
  label?: string;
  accept?: string;
  helper?: string;
  modifiers?: string;
  multiple?: boolean;
  placeholder?: string;
  value?: File[] | null;
  iconPosition?: 'left' | 'right';
}>();

const randomId = ref(generateRandomId());
const currentValue = ref(props.value || []);
const parsedLabel = computed(() => markdown(props.label));
const parsedHelper = computed(() => markdown(props.helper));
const className = computed(() => buildClass('ui-file-picker', (props.modifiers || '') + (props.multiple ? ' multiple' : '')));
const currentPlaceholder = computed(() => ((currentValue.value.length > 0)
  ? currentValue.value.map((file) => file.name).join(', ')
  : props.placeholder));

// -------------------------------------------------------------------------------------------------
// CALLBACKS DECLARATION.
// -------------------------------------------------------------------------------------------------

const handleChange = (event: InputEvent): void => {
  const files = [];
  const target = event.target as HTMLInputElement;
  const numberOfFiles = target.files.length;
  for (let index = 0; index < numberOfFiles; index += 1) {
    files.push(target.files[index]);
  }
  currentValue.value = files;
  emit('change', currentValue.value, event);
};

// -------------------------------------------------------------------------------------------------
// PROPS REACTIVITY MANAGEMENT.
// -------------------------------------------------------------------------------------------------

// Updates current value whenever `value` prop changes.
watch(() => props.value, () => {
  currentValue.value = props.value;
});
</script>

<template>
  <div
    :id="id"
    :class="className"
  >
    <label
      v-if="label !== undefined"
      class="ui-file-picker__label"
      :for="randomId"
      v-html="parsedLabel"
    />
    <div class="ui-file-picker__wrapper">
      <UIIcon
        v-if="icon !== undefined && iconPosition !== 'right'"
        :name="icon"
      />
      <input
        :id="randomId"
        type="file"
        :name="name"
        :accept="accept"
        :multiple="multiple"
        class="ui-file-picker__wrapper__field"
        :tabindex="modifiers?.includes('disabled') ? -1 : 0"
        @change="handleChange"
        @blur="$emit('blur', currentValue, $event)"
        @focus="$emit('focus', currentValue, $event)"
      >
      <UIIcon
        v-if="icon !== undefined && iconPosition === 'right'"
        :name="icon"
      />
      <span class="ui-file-picker__wrapper__placeholder">
        {{ currentPlaceholder }}
      </span>
    </div>
    <span
      v-if="helper !== undefined"
      class="ui-file-picker__helper"
      v-html="parsedHelper"
    />
  </div>
</template>

// library/src/scripts/svelte/FilePicker.svelte
<!-- File picker. -->
<script lang="ts">
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import { createEventDispatcher } from 'svelte';
import UIIcon from 'scripts/svelte/Icon.svelte';
import markdown from 'scripts/helpers/markdown';
import buildClass from 'scripts/helpers/buildClass';
import generateRandomId from 'scripts/helpers/generateRandomId';

const dispatch = createEventDispatcher();

export let name: string;
export let modifiers = '';
export let multiple = false;
export let value: File[] = [];
export let id: string | undefined = undefined;
export let icon: string | undefined = undefined;
export let label: string | undefined = undefined;
export let accept: string | undefined = undefined;
export let helper: string | undefined = undefined;
export let iconPosition: 'left' | 'right' = 'left';
export let placeholder: string | undefined = undefined;

let currentValue = value;
const randomId = generateRandomId();

$: className = buildClass('ui-file-picker', modifiers + (multiple ? ' multiple' : ''));
$: parsedLabel = label !== null ? markdown(label) : null;
$: parsedHelper = helper !== null ? markdown(helper) : null;
$: currentPlaceholder = (currentValue.length > 0) ? currentValue.map((file) => file.name).join(', ') : placeholder;

// -----------------------------------------------------------------------------------------------
// CALLBACKS DECLARATION.
// -----------------------------------------------------------------------------------------------

const handleChange = (event: Event): void => {
  const files = [];
  const target = event.target as HTMLInputElement;
  const numberOfFiles = (target.files as FileList).length;
  for (let index = 0; index < numberOfFiles; index += 1) {
    files.push((target.files as FileList)[index]);
  }
  currentValue = files;
  dispatch('change', [files, event]);
};

const handleFocus = (event: FocusEvent): void => {
  dispatch('focus', [currentValue, event]);
};

const handleBlur = (event: FocusEvent): void => {
  dispatch('blur', [currentValue, event]);
};

// -------------------------------------------------------------------------------------------------
// PROPS REACTIVITY MANAGEMENT.
// -------------------------------------------------------------------------------------------------

// Updates current value whenever `value` prop changes.
const updateValue = (updatedValue: File[]) => {
  currentValue = updatedValue;
};
$: updateValue(value);
</script>

<div
  id={id}
  class={className}
>
  {#if label !== null}
    <label for={randomId} class="ui-file-picker__label">
      {@html parsedLabel}
    </label>
  {/if}
  <div class="ui-file-picker__wrapper">
    {#if icon !== null && iconPosition === 'left'}
      <UIIcon name={icon} />
    {/if}
    <input
      type="file"
      name={name}
      id={randomId}
      accept={accept}
      multiple={multiple}
      on:blur={handleBlur}
      on:focus={handleFocus}
      on:input={handleChange}
      class="ui-file-picker__wrapper__field"
      tabIndex={modifiers.includes('disabled') ? -1 : 0}
    >
    {#if icon !== null && iconPosition === 'right'}
      <UIIcon name={icon} />
    {/if}
    <span class="ui-file-picker__wrapper__placeholder">
      {currentPlaceholder}
    </span>
  </div>
  {#if helper !== null}
    <span  class="ui-file-picker__helper">
      {@html parsedHelper}
    </span>
  {/if}
</div>
