// library/src/scripts/react/Link.tsx
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import * as React from 'react';
import buildClass from 'scripts/helpers/buildClass';

/**
 * Hyperlink.
 */
function UILink(props: UILinkProps & {
  /** `click` event handler. */
  onClick?: React.MouseEventHandler<HTMLAnchorElement>;
}): JSX.Element {
  const { rel, id } = props;
  const { href, label } = props;
  const { onClick, modifiers = '', target } = props;

  return (
    <a
      id={id}
      rel={rel}
      href={href}
      target={target}
      onClick={onClick}
      className={buildClass('ui-link', modifiers)}
    >
      {label}
    </a>
  );
}

export default React.memo(UILink);

// library/src/scripts/svelte/Link.svelte
<!-- Hyperlink. -->
<script lang="ts">
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import markdown from 'scripts/helpers/markdown';
import buildClass from 'scripts/helpers/buildClass';

export let href: string;
export let label: string;
export let modifiers = '';
export let id: string | undefined = undefined;
export let rel: string | undefined = undefined;
export let target: string | undefined = undefined;
export let onClick: ((event: MouseEvent) => void) | undefined = undefined;

$: className = buildClass('ui-link', modifiers);
</script>

<a {id} {rel} {href} class={className} {target} on:click={onClick}>
  {@html markdown(label)}
</a>
