// library/src/scripts/vue/Textfield.vue
<!-- Text field. -->
<script lang="ts" setup>
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import {
  computed,
  onUpdated,
  ref, watch,
} from 'vue';
import UIIcon from 'scripts/vue/Icon.vue';
import markdown from 'scripts/helpers/markdown';
import buildClass from 'scripts/helpers/buildClass';
import generateRandomId from 'scripts/helpers/generateRandomId';

type KeyType = 'default' | 'ctrlKey' | 'altKey' | 'shiftKey' | 'metaKey';
type AllowedKeys = Record<KeyType, RegExp | null>;
type Transform = (value: string, selectionStart: number) => [string, number?];

const emit = defineEmits({
  focus: null,
  blur: null,
  paste: null,
  change: null,
  keyDown: null,
  iconClick: null,
  iconKeyDown: null,
});

const props = defineProps<{
  id?: string;
  min?: number;
  max?: number;
  name: string;
  step?: number;
  icon?: string;
  size?: number;
  label?: string;
  helper?: string;
  readonly?: boolean;
  maxlength?: number;
  modifiers?: string;
  autofocus?: boolean;
  placeholder?: string;
  value?: string | null;
  autocomplete?: 'on' | 'off';
  iconPosition?: 'left' | 'right';
  allowedKeys?: {
    altKey?: RegExp;
    metaKey?: RegExp;
    ctrlKey?: RegExp;
    default?: RegExp;
    shiftKey?: RegExp;
  };
  debounceTimeout?: number;
  type?: 'text' | 'email' | 'number' | 'password' | 'search' | 'tel' | 'url';
  transform?: Transform;
}>();

const keyTypes: KeyType[] = ['default', 'ctrlKey', 'altKey', 'shiftKey', 'metaKey'];
const specialKeysRegexp = /Tab|Control|Shift|Meta|ContextMenu|Alt|Escape|Insert|Home|End|AltGraph|NumLock|Backspace|Delete|Enter|ArrowRight|ArrowLeft|ArrowDown|ArrowUp/;
const defaultTransform = (value: string): string[] => [value];

const timeout = ref(null);
const inputRef = ref(null);
const reverseTimeout = ref(null);
const cursorPosition = ref(null);
const randomId = ref(generateRandomId());
const parsedLabel = computed(() => markdown(props.label));
const parsedHelper = computed(() => markdown(props.helper));
const isDisabled = computed(() => props.modifiers?.includes('disabled'));
const actualTransform = computed(() => props.transform || defaultTransform);
const className = computed(() => buildClass('ui-textfield', props.modifiers || ''));
const currentValue = ref(actualTransform.value(props.value || '', 0)[0]);

// Memoïzes global version of allowed keys RegExps (required for filtering out a whole text).
const globalAllowedKeys = computed(() => keyTypes.reduce((allAllowedKeys, keyType) => {
  const allowedKeysForType = (props.allowedKeys || {})[keyType];
  return {
    ...allAllowedKeys,
    [keyType]: (allowedKeysForType !== undefined && allowedKeysForType !== null)
      ? new RegExp(allowedKeysForType.source, `${allowedKeysForType.flags}g`)
      : null,
  };
}, {} as AllowedKeys));

// -------------------------------------------------------------------------------------------------
// CALLBACKS DECLARATION.
// -------------------------------------------------------------------------------------------------

const handleChange = (event: InputEvent, filter = true): void => {
  clearTimeout(timeout.value);
  clearTimeout(reverseTimeout.value);
  const target = event.target as HTMLInputElement;
  const { selectionStart } = target;
  const filteredValue = (filter && globalAllowedKeys.value.default !== null)
    ? (target.value.match(globalAllowedKeys.value.default) || []).join('')
    : target.value;
  const [newValue, newCursorPosition] = actualTransform.value(filteredValue, selectionStart);
  if (newCursorPosition !== undefined) {
    cursorPosition.value = newCursorPosition;
  } else {
    const isAtTheEnd = selectionStart >= currentValue.value.length;
    cursorPosition.value = isAtTheEnd ? newValue.length : selectionStart;
  }
  // We need to force the input value to prevent the component from getting uncontrolled.
  if (newValue === currentValue.value) {
    target.value = currentValue.value;
  } else {
    currentValue.value = newValue;
  }
  // This debounce system prevents triggering `onChange` callback too many times when user is
  // still typing to improve performance and make UI more reactive on low-perfomance devices.
  timeout.value = setTimeout(() => {
    emit('change', newValue, event);
  }, props.debounceTimeout || 0);
};

const handleKeyDown = (event: KeyboardEvent): void => {
  const allowedKeys = props.allowedKeys || {};
  let allowedKeysForEvent = allowedKeys.default || null;
  if (event.ctrlKey === true) {
    allowedKeysForEvent = allowedKeys.ctrlKey || null;
  } else if (event.shiftKey === true) {
    allowedKeysForEvent = allowedKeys.shiftKey || null;
  } else if (event.altKey === true) {
    allowedKeysForEvent = allowedKeys.altKey || null;
  } else if (event.metaKey === true) {
    allowedKeysForEvent = allowedKeys.metaKey || null;
  }
  if (
    allowedKeysForEvent !== null
    && !allowedKeysForEvent.test(event.key)
    && !specialKeysRegexp.test(event.key)
  ) {
    event.preventDefault();
  } else {
    emit('keyDown', event);
  }
};

const handlePaste = (event: ClipboardEvent): void => {
  // `selectionStart` and `selectionEnd` do not exist on inputs with type `number`, so we just
  // want to replace the entire content when pasting something in that case.
  const selectionStart = (event.target as HTMLInputElement).selectionStart || 0;
  const selectionEnd = (event.target as HTMLInputElement).selectionEnd || currentValue.value.length;
  const filteredValue = (globalAllowedKeys.value.default !== null)
    ? (event.clipboardData.getData('text').match(globalAllowedKeys.value.default) || []).join('')
    : event.clipboardData.getData('text');
  handleChange({
    target: {
      value: `${currentValue.value.slice(0, selectionStart)}${filteredValue}${currentValue.value.slice(selectionEnd)}`,
      selectionStart: selectionStart + filteredValue.length,
    },
  } as unknown as InputEvent, false);
  event.preventDefault();
  emit('paste', event);
};

// -------------------------------------------------------------------------------------------------
// PROPS REACTIVITY MANAGEMENT.
// -------------------------------------------------------------------------------------------------

// Updates current value whenever `value` and `transform` props change.
watch(() => [props.value, props.transform], () => {
  clearTimeout(reverseTimeout.value);
  // Do not update current value immediatly while user is typing something else.
  reverseTimeout.value = setTimeout(() => {
    const [newValue] = actualTransform.value(props.value || '', 0);
    currentValue.value = newValue;
  }, 150);
});

// Re-positions cursor at the right place when using transform function.
onUpdated(() => {
  if (/^(url|text|tel|search|password)$/.test(props.type || 'text') && inputRef.value !== null) {
    inputRef.value.selectionStart = cursorPosition.value;
    inputRef.value.selectionEnd = cursorPosition.value;
  }
});
</script>

<template>
  <div
    :id="id"
    :class="className"
  >
    <label
      v-if="label !== undefined"
      class="ui-textfield__label"
      :for="randomId"
      v-html="parsedLabel"
    />
    <div class="ui-textfield__wrapper">
      <span
        v-if="icon !== undefined && iconPosition !== 'right'"
        tabIndex="0"
        role="button"
        class="ui-textfield__wrapper__icon"
        @click="$emit('iconClick', $event)"
        @keydown="$emit('iconKeyDown', $event)"
      >
        <UIIcon :name="icon" />
      </span>
      <input
        :id="randomId"
        ref="inputRef"
        :name="name"
        :max="max"
        :min="min"
        :step="step"
        :type="type"
        :readonly="readonly"
        :value="currentValue"
        :maxlength="maxlength"
        :placeholder="placeholder"
        :autofocus="autofocus"
        :autocomplete="autocomplete"
        class="ui-textfield__wrapper__field"
        :disabled="isDisabled"
        :size="size === undefined ? 1 : size"
        @keydown="handleKeyDown"
        @blur="$emit('blur', currentValue, $event)"
        @focus="$emit('focus', currentValue, $event)"
        @paste="(readonly !== true && !isDisabled) ? handlePaste($event) : undefined"
        @input="(readonly !== true && !isDisabled) ? handleChange($event) : undefined"
      >
      <span
        v-if="icon !== undefined && iconPosition === 'right'"
        tabIndex="0"
        role="button"
        class="ui-textfield__wrapper__icon"
        @click="$emit('iconClick', $event)"
        @keydown="$emit('iconKeyDown', $event)"
      >
        <UIIcon :name="icon" />
      </span>
    </div>
    <span
      v-if="helper !== undefined"
      class="ui-textfield__helper"
      v-html="parsedHelper"
    />
  </div>
</template>

// library/src/scripts/svelte/Textfield.svelte
<!-- Text field. -->
<script lang="ts">
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import UIIcon from 'scripts/svelte/Icon.svelte';
import markdown from 'scripts/helpers/markdown';
import buildClass from 'scripts/helpers/buildClass';
import { createEventDispatcher, tick } from 'svelte';
import generateRandomId from 'scripts/helpers/generateRandomId';

type KeyType = 'default' | 'ctrlKey' | 'altKey' | 'shiftKey' | 'metaKey';
type AllowedKeys = Partial<Record<KeyType, RegExp | null>>;
type Transform = (value: string, selectionStart: number) => [string, number?];

const dispatch = createEventDispatcher();
const defaultTransform: Transform = (newValue) => [newValue];
const keyTypes: KeyType[] = ['default', 'ctrlKey', 'altKey', 'shiftKey', 'metaKey'];
const specialKeysRegexp = /Tab|Control|Shift|Meta|ContextMenu|Alt|Escape|Insert|Home|End|AltGraph|NumLock|Backspace|Delete|Enter|ArrowRight|ArrowLeft|ArrowDown|ArrowUp/;

export let value = '';
export let name: string;
export let modifiers = '';
export let readonly = false;
export let autofocus = false;
export let debounceTimeout = 0;
export let id: string | null = null;
export let min: number | null = null;
export let max: number | null = null;
export let step: number | null = null;
export let size: number | null = null;
export let icon: string | null = null;
export let label: string | null = null;
export let helper: string | null = null;
export let allowedKeys: AllowedKeys = {};
export let maxlength: number | null = null;
export let placeholder: string | null = null;
export let autocomplete: 'on' | 'off' = 'on';
export let iconPosition: 'left' | 'right' = 'left';
export let transform: Transform | null = defaultTransform;
export let type: 'text' | 'email' | 'number' | 'password' | 'search' | 'tel' | 'url' = 'text';

// Enforces props default values.
$: id = id || null;
$: icon = icon || null;
$: value = value || '';
$: type = type || 'text';
$: label = label || null;
$: helper = helper || null;
$: modifiers = modifiers || '';
$: readonly = readonly || false;
$: autofocus = autofocus || false;
$: allowedKeys = allowedKeys || {};
$: placeholder = placeholder || null;
$: autocomplete = autocomplete || 'on';
$: iconPosition = iconPosition || 'left';
$: debounceTimeout = debounceTimeout || 0;
$: min = (min !== undefined) ? min : null;
$: max = (max !== undefined) ? max : null;
$: step = (step !== undefined) ? step : null;
$: size = (size !== undefined) ? size : null;
$: transform = transform || defaultTransform;
$: maxlength = (maxlength !== undefined) ? maxlength : null;

const randomId = generateRandomId();
let timeout: number | null = null;
let cursorPosition: number | null = null;
let reverseTimeout: number | null = null;
const actualTransform = transform || defaultTransform;
let currentValue = defaultTransform(value, 0)[0];
let inputRef: HTMLInputElement | null = null;

$: isDisabled = modifiers.includes('disabled');
$: className = buildClass('ui-textfield', modifiers);
$: parsedLabel = label !== null ? markdown(label) : null;
$: parsedHelper = helper !== null ? markdown(helper) : null;
// Memoïzes global version of allowed keys RegExps (required for filtering out a whole text).
$: globalAllowedKeys = keyTypes.reduce((allAllowedKeys, keyType) => {
  const allowedKeysForType = allowedKeys[keyType];
  return {
    ...allAllowedKeys,
    [keyType]: (allowedKeysForType !== undefined && allowedKeysForType !== null)
      ? new RegExp(allowedKeysForType.source, `${allowedKeysForType.flags}g`)
      : null,
  };
}, {} as AllowedKeys);

// -------------------------------------------------------------------------------------------------
// CALLBACKS DECLARATION.
// -------------------------------------------------------------------------------------------------

// Re-positions cursor at the right place when using transform function.
const updateCursorPosition = async () => {
  await tick();
  if (/^(url|text|tel|search|password)$/.test(type || 'text') && inputRef !== null) {
    inputRef.selectionStart = cursorPosition;
    inputRef.selectionEnd = cursorPosition;
  }
};

const handleChange = (event: Event, filter = true): void => {
  clearTimeout(timeout as number);
  clearTimeout(reverseTimeout as number);
  const target = event.target as HTMLInputElement;
  const selectionStart = target.selectionStart as number;
  const filteredValue = (filter && globalAllowedKeys.default !== null)
    ? (target.value.match(globalAllowedKeys.default as RegExp) || []).join('')
    : target.value;
  const [newValue, newCursorPosition] = actualTransform(filteredValue, selectionStart);
  if (newCursorPosition !== undefined) {
    cursorPosition = newCursorPosition;
  } else {
    const isAtTheEnd = selectionStart >= currentValue.length;
    cursorPosition = isAtTheEnd ? newValue.length : selectionStart;
  }
  // We need to force the input value to prevent the component from getting uncontrolled.
  if (newValue === currentValue) {
    target.value = currentValue;
  } else {
    currentValue = newValue;
  }
  // This debounce system prevents triggering `onChange` callback too many times when user is
  // still typing to improve performance and make UI more reactive on low-perfomance devices.
  timeout = setTimeout(() => {
    dispatch('change', { newValue, event });
  }, debounceTimeout) as unknown as number;
  updateCursorPosition();
};

const handleKeyDown = (event: KeyboardEvent): void => {
  let allowedKeysForEvent = allowedKeys.default || null;
  if (event.ctrlKey === true) {
    allowedKeysForEvent = allowedKeys.ctrlKey || null;
  } else if (event.shiftKey === true) {
    allowedKeysForEvent = allowedKeys.shiftKey || null;
  } else if (event.altKey === true) {
    allowedKeysForEvent = allowedKeys.altKey || null;
  } else if (event.metaKey === true) {
    allowedKeysForEvent = allowedKeys.metaKey || null;
  }
  if (
    allowedKeysForEvent !== null
    && !allowedKeysForEvent.test(event.key)
    && !specialKeysRegexp.test(event.key)
  ) {
    event.preventDefault();
  } else {
    dispatch('keyDown', { event });
  }
};

const handlePaste = (event: ClipboardEvent): void => {
  const clipboardData = event.clipboardData as DataTransfer;
  // `selectionStart` and `selectionEnd` do not exist on inputs with type `number`, so we just
  // want to replace the entire content when pasting something in that case.
  const selectionStart = (event.target as HTMLInputElement).selectionStart || 0;
  const selectionEnd = (event.target as HTMLInputElement).selectionEnd || currentValue.length;
  const filteredValue = (globalAllowedKeys.default !== null)
    ? (clipboardData.getData('text').match(globalAllowedKeys.default as RegExp) || []).join('')
    : clipboardData.getData('text');
  handleChange({
    target: {
      value: `${currentValue.slice(0, selectionStart)}${filteredValue}${currentValue.slice(selectionEnd)}`,
      selectionStart: selectionStart + filteredValue.length,
    },
  } as unknown as InputEvent, false);
  event.preventDefault();
  dispatch('paste', { event });
};

const handleBlur = (event: FocusEvent): void => {
  dispatch('blur', { event, currentValue });
};

const handleFocus = (event: FocusEvent): void => {
  dispatch('focus', { event, currentValue });
};

const handleIconClick = (event: MouseEvent): void => {
  dispatch('iconClick', event);
};

const handleIconKeyDown = (event: KeyboardEvent): void => {
  dispatch('iconKeyDown', event);
};

// -------------------------------------------------------------------------------------------------
// PROPS REACTIVITY MANAGEMENT.
// -------------------------------------------------------------------------------------------------

// Updates current value whenever `value` and `transform` props change.
$: {
  clearTimeout(reverseTimeout as number);
  // Do not update current value immediatly while user is typing something else.
  reverseTimeout = setTimeout(() => {
    const [newValue] = (transform as Transform)(value as string, 0);
    currentValue = newValue;
    updateCursorPosition();
  }, 150) as unknown as number;
}
</script>

<!-- svelte-ignore a11y-autofocus -->
<div
id={id}
  class={className}
>
  {#if label !== null}
    <label for={randomId} class="ui-textfield__label">
      {@html parsedLabel}
    </label>
  {/if}
  <div class="ui-textfield__wrapper">
    {#if icon !== null && iconPosition === 'left'}
      <span
        tabIndex="0"
        role="button"
        class="ui-textfield__wrapper__icon"
        on:click={handleIconClick}
        on:keydown={handleIconKeyDown}
      >
        <UIIcon name={icon} />
      </span>
    {/if}
    <input
      max={max}
      min={min}
      name={name}
      step={step}
      size={size}
      type={type}
      id={randomId}
      readonly={readonly}
      bind:this={inputRef}
      on:blur={handleBlur}
      value={currentValue}
      maxlength={maxlength}
      autofocus={autofocus}
      disabled={isDisabled}
      on:focus={handleFocus}
      placeholder={placeholder}
      on:keydown={handleKeyDown}
      autocomplete={autocomplete}
      class="ui-textfield__wrapper__field"
      on:paste={(readonly !== true && !isDisabled) ? handlePaste : null}
      on:input={(readonly !== true && !isDisabled) ? handleChange : null}
    >
    {#if icon !== null && iconPosition === 'right'}
      <span
        tabIndex="0"
        role="button"
        class="ui-textfield__wrapper__icon"
        on:click={handleIconClick}
        on:keydown={handleIconKeyDown}
      >
        <UIIcon name={icon} />
      </span>
    {/if}
  </div>
  {#if helper !== null}
    <span  class="ui-textfield__helper">
      {@html parsedHelper}
    </span>
  {/if}
</div>
