// library/src/scripts/react/Textfield.tsx
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import * as React from 'react';
import UIIcon from 'scripts/react/Icon';
import markdown from 'scripts/helpers/markdown';
import buildClass from 'scripts/helpers/buildClass';
import generateRandomId from 'scripts/helpers/generateRandomId';

type KeyType = 'default' | 'ctrlKey' | 'altKey' | 'shiftKey' | 'metaKey';
type AllowedKeys = Record<KeyType, RegExp | null>;

const JSXUIIcon = UIIcon as JSXElement;

const keyTypes: KeyType[] = ['default', 'ctrlKey', 'altKey', 'shiftKey', 'metaKey'];
const specialKeysRegexp = /Tab|Control|Shift|Meta|ContextMenu|Alt|Escape|Insert|Home|End|AltGraph|NumLock|Backspace|Delete|Enter|ArrowRight|ArrowLeft|ArrowDown|ArrowUp/;
const defaultTransform = (value: string): [string, number?] => [value];

/**
 * Text field.
 */
function UITextfield(props: UITextfieldProps): JSX.Element {
  const { min, max } = props;
  const { maxlength, onFocus } = props;
  const { type = 'text', size } = props;
  const { id, modifiers = '', label } = props;
  const { autofocus = false, onPaste } = props;
  const { helper, onChange, value = '' } = props;
  const { name, transform = defaultTransform } = props;
  const { iconPosition = 'left', icon, onBlur } = props;
  const { onIconKeyDown, readonly = false, step } = props;
  const { onIconClick, autocomplete = 'off', placeholder } = props;
  const { debounceTimeout = 50, allowedKeys = {}, onKeyDown } = props;

  const isUserTyping = React.useRef(false);
  const [randomId] = React.useState(generateRandomId);
  const inputRef = React.useRef<HTMLInputElement>(null);
  const timeout = React.useRef<NodeJS.Timeout | null>(null);
  const isDisabled = (modifiers).includes('disabled');
  const className = buildClass('ui-textfield', modifiers);
  const [cursorPosition, setCursorPosition] = React.useState<number | null>(null);
  const [currentValue, setCurrentValue] = React.useState(() => transform(value, 0)[0]);

  // Memoizes global version of allowed keys RegExps (required for filtering out a whole text).
  const globalAllowedKeys = React.useMemo(() => keyTypes.reduce((allAllowedKeys, keyType) => {
    const allowedKeysForType = (allowedKeys as AllowedKeys)[keyType];
    return {
      ...allAllowedKeys,
      [keyType]: (allowedKeysForType !== undefined && allowedKeysForType !== null)
        ? new RegExp(allowedKeysForType.source, `${allowedKeysForType.flags}g`)
        : null,
    };
  }, {} as AllowedKeys), [allowedKeys]);

  // -----------------------------------------------------------------------------------------------
  // CALLBACKS DECLARATION.
  // -----------------------------------------------------------------------------------------------

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>, filter = true): void => {
    clearTimeout(timeout.current as NodeJS.Timeout);
    isUserTyping.current = true;
    const filteredValue = (filter && globalAllowedKeys.default !== null)
      ? (event.target.value.match(globalAllowedKeys.default) || []).join('')
      : event.target.value;
    const selectionStart = event.target.selectionStart as number;
    const [newValue, newCursorPosition] = transform(filteredValue, selectionStart);
    setCurrentValue(newValue);
    if (newCursorPosition !== undefined) {
      setCursorPosition(newCursorPosition);
    } else {
      // At this point, the input's value has already changed, which means the cursor's position is
      // at n + 1, which is why we substract 1 when checking last position.
      const currentCursorPosition = selectionStart;
      const isAtTheEnd = currentCursorPosition - 1 >= currentValue.length;
      setCursorPosition(isAtTheEnd ? newValue.length : currentCursorPosition);
    }
    // This debounce system prevents triggering `onChange` callback too many times when user is
    // still typing to improve performance and make UI more reactive on low-perfomance devices.
    timeout.current = setTimeout(() => {
      isUserTyping.current = false;
      if (onChange !== undefined) {
        onChange(newValue, event as unknown as InputEvent);
      }
    }, debounceTimeout);
  };

  const handleKeyDown = (event: React.KeyboardEvent<HTMLInputElement>): void => {
    let allowedKeysForEvent = (allowedKeys as AllowedKeys).default || null;
    if (event.ctrlKey === true) {
      allowedKeysForEvent = (allowedKeys as AllowedKeys).ctrlKey || null;
    } else if (event.shiftKey === true) {
      allowedKeysForEvent = (allowedKeys as AllowedKeys).shiftKey || null;
    } else if (event.altKey === true) {
      allowedKeysForEvent = (allowedKeys as AllowedKeys).altKey || null;
    } else if (event.metaKey === true) {
      allowedKeysForEvent = (allowedKeys as AllowedKeys).metaKey || null;
    }
    if (
      allowedKeysForEvent !== null
      && !allowedKeysForEvent.test(event.key)
      && !specialKeysRegexp.test(event.key)
    ) {
      event.preventDefault();
    } else if (onKeyDown) {
      onKeyDown(currentValue, event as unknown as KeyboardEvent);
    }
  };

  const handlePaste = (event: React.ClipboardEvent<HTMLInputElement>): void => {
    // `selectionStart` and `selectionEnd` do not exist on inputs with type `number`, so we just
    // want to replace the entire content when pasting something in that case.
    const selectionStart = (event.target as HTMLInputElement).selectionStart || 0;
    const selectionEnd = (event.target as HTMLInputElement).selectionEnd || currentValue.length;
    const filteredValue = (globalAllowedKeys.default !== null)
      ? (event.clipboardData.getData('text').match(globalAllowedKeys.default) || []).join('')
      : event.clipboardData.getData('text');
    handleChange({
      target: {
        value: `${currentValue.slice(0, selectionStart)}${filteredValue}${currentValue.slice(selectionEnd)}`,
        selectionStart: selectionStart + filteredValue.length,
      },
    } as unknown as React.ChangeEvent<HTMLInputElement>, false);
    event.preventDefault();
    if (onPaste !== undefined) {
      onPaste(currentValue, event as unknown as ClipboardEvent);
    }
  };

  const handleBlur = (event: React.FocusEvent<HTMLInputElement>): void => {
    if (onBlur !== undefined) {
      onBlur(currentValue, event as unknown as FocusEvent);
    }
  };

  const handleFocus = (event: React.FocusEvent<HTMLInputElement>): void => {
    if (onFocus !== undefined) {
      onFocus(currentValue, event as unknown as FocusEvent);
    }
  };

  // -----------------------------------------------------------------------------------------------
  // PROPS REACTIVITY MANAGEMENT.
  // -----------------------------------------------------------------------------------------------

  // Updates current value whenever `value` and `transform` props change.
  React.useEffect(() => {
    // Do not update current value immediatly while user is typing something else.
    if (!isUserTyping.current) {
      const [newValue] = transform(value, 0);
      setCurrentValue(newValue);
    }
  }, [value, transform]);

  // Re-positions cursor at the right place when using transform function.
  React.useEffect(() => {
    if (/^(url|text|tel|search|password)$/.test(type)) {
      (inputRef.current as HTMLInputElement).selectionStart = cursorPosition;
      (inputRef.current as HTMLInputElement).selectionEnd = cursorPosition;
    }
  }, [currentValue, cursorPosition, type]);

  // -----------------------------------------------------------------------------------------------
  // COMPONENT RENDERING.
  // -----------------------------------------------------------------------------------------------

  const children = [
    (icon !== undefined)
      ? (
        <span
          key="icon"
          tabIndex={0}
          role="button"
          className="ui-textfield__wrapper__icon"
          onClick={onIconClick as unknown as React.MouseEventHandler<HTMLSpanElement>}
          onKeyDown={onIconKeyDown as unknown as React.KeyboardEventHandler<HTMLSpanElement>}
        >
          <JSXUIIcon name={icon} />
        </span>
      )
      : null,
    <input
      key="input"
      max={max}
      min={min}
      step={step}
      size={size}
      type={type}
      name={name}
      id={randomId}
      ref={inputRef}
      disabled={isDisabled}
      onBlur={handleBlur}
      onFocus={handleFocus}
      value={currentValue}
      readOnly={readonly}
      maxLength={maxlength}
      autoFocus={autofocus}
      placeholder={placeholder}
      autoComplete={autocomplete}
      className="ui-textfield__wrapper__field"
      onPaste={(!readonly && !isDisabled) ? handlePaste : undefined}
      onChange={(!readonly && !isDisabled) ? handleChange : undefined}
      onKeyDown={(!readonly && !isDisabled) ? handleKeyDown : undefined}
    />,
  ];

  return (
    <div
      id={id}
      className={className}
    >
      {(label !== undefined) && (
        <label
          className="ui-textfield__label"
          htmlFor={randomId}
          dangerouslySetInnerHTML={{ __html: markdown(label) }}
        />
      )}
      <div className="ui-textfield__wrapper">
        {(iconPosition === 'left') ? children : children.reverse()}
      </div>
      {(helper !== undefined) && (
        <span
          className="ui-textfield__helper"
          dangerouslySetInnerHTML={{ __html: markdown(helper) }}
        />
      )}
    </div>
  );
}

export default React.memo(UITextfield);

// library/src/scripts/svelte/Textfield.svelte
<!-- Text field. -->
<script lang="ts">
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import { tick } from 'svelte';
import UIIcon from 'scripts/svelte/Icon.svelte';
import markdown from 'scripts/helpers/markdown';
import buildClass from 'scripts/helpers/buildClass';
import generateRandomId from 'scripts/helpers/generateRandomId';

type KeyType = 'default' | 'ctrlKey' | 'altKey' | 'shiftKey' | 'metaKey';
type AllowedKeys = Partial<Record<KeyType, RegExp>>;
type Transform = (value: string, selectionStart: number) => [string, number?];

const defaultTransform: Transform = (newValue) => [newValue];
const keyTypes: KeyType[] = ['default', 'ctrlKey', 'altKey', 'shiftKey', 'metaKey'];
const specialKeysRegexp = /Tab|Control|Shift|Meta|ContextMenu|Alt|Escape|Insert|Home|End|AltGraph|NumLock|Backspace|Delete|Enter|ArrowRight|ArrowLeft|ArrowDown|ArrowUp/;

export let value = '';
export let name: string;
export let modifiers = '';
export let readonly = false;
export let autofocus = false;
export let debounceTimeout = 50;
export let allowedKeys: AllowedKeys = {};
export let autocomplete: 'on' | 'off' = 'on';
export let id: string | undefined = undefined;
export let min: number | undefined = undefined;
export let max: number | undefined = undefined;
export let step: number | undefined = undefined;
export let size: number | undefined = undefined;
export let icon: string | undefined = undefined;
export let label: string | undefined = undefined;
export let helper: string | undefined = undefined;
export let iconPosition: 'left' | 'right' = 'left';
export let maxlength: number | undefined = undefined;
export let placeholder: string | undefined = undefined;
export let transform: Transform | undefined = defaultTransform;
export let type: 'text' | 'email' | 'number' | 'password' | 'search' | 'tel' | 'url' = 'text';
export let onFocus: ((value: string, event: FocusEvent) => void) | undefined = undefined;
export let onBlur: ((value: string, event: FocusEvent) => void) | undefined = undefined;
export let onPaste: ((value: string, event: ClipboardEvent) => void) | undefined = undefined;
export let onChange: ((value: string, event: InputEvent) => void) | undefined = undefined;
export let onKeyDown: ((value: string, event: KeyboardEvent) => void) | undefined = undefined;
export let onIconKeyDown: ((event: KeyboardEvent) => void) | undefined = undefined;
export let onIconClick: ((event: MouseEvent) => void) | undefined = undefined;

let userIsTyping = false;
const randomId = generateRandomId();
let timeout: number | null = null;
let cursorPosition: number | null = null;
let currentValue = defaultTransform(value, 0)[0];
let inputRef: HTMLInputElement | null = null;

$: isDisabled = modifiers.includes('disabled');
$: className = buildClass('ui-textfield', modifiers);
// Memoizes global version of allowed keys RegExps (required for filtering out a whole text).
$: globalAllowedKeys = keyTypes.reduce((allAllowedKeys, keyType) => {
  const allowedKeysForType = allowedKeys[keyType];
  return {
    ...allAllowedKeys,
    [keyType]: (allowedKeysForType !== undefined)
      ? new RegExp(allowedKeysForType.source, `${allowedKeysForType.flags}g`)
      : null,
  };
}, {} as AllowedKeys);

// -------------------------------------------------------------------------------------------------
// CALLBACKS DECLARATION.
// -------------------------------------------------------------------------------------------------

// Re-positions cursor at the right place when using transform function.
const updateCursorPosition = async () => {
  await tick();
  if (/^(url|text|tel|search|password)$/.test(type || 'text') && inputRef !== null) {
    inputRef.selectionStart = cursorPosition;
    inputRef.selectionEnd = cursorPosition;
  }
};

const handleChange = (event: Event, filter = true): void => {
  clearTimeout(timeout as number);
  userIsTyping = true;
  const target = event.target as HTMLInputElement;
  const selectionStart = target.selectionStart as number;
  const filteredValue = (filter && globalAllowedKeys.default !== null)
    ? (target.value.match(globalAllowedKeys.default as RegExp) || []).join('')
    : target.value;
  const [newValue, newCursorPosition] = (transform as Transform)(filteredValue, selectionStart);
  if (newCursorPosition !== undefined) {
    cursorPosition = newCursorPosition;
  } else {
    const isAtTheEnd = selectionStart >= currentValue.length;
    cursorPosition = isAtTheEnd ? newValue.length : selectionStart;
  }
  // We need to force the input value to prevent the component from getting uncontrolled.
  if (newValue === currentValue) {
    target.value = currentValue;
  } else {
    currentValue = newValue;
  }
  // This debounce system prevents triggering `onChange` callback too many times when user is
  // still typing to improve performance and make UI more reactive on low-perfomance devices.
  timeout = setTimeout(() => {
    userIsTyping = false;
    if (onChange !== undefined) {
      onChange(newValue, event as InputEvent);
    }
  }, debounceTimeout) as unknown as number;
  updateCursorPosition();
};

const handleKeyDown = (event: KeyboardEvent): void => {
  let allowedKeysForEvent = allowedKeys.default;
  if (event.ctrlKey === true) {
    allowedKeysForEvent = allowedKeys.ctrlKey;
  } else if (event.shiftKey === true) {
    allowedKeysForEvent = allowedKeys.shiftKey;
  } else if (event.altKey === true) {
    allowedKeysForEvent = allowedKeys.altKey;
  } else if (event.metaKey === true) {
    allowedKeysForEvent = allowedKeys.metaKey;
  }
  if (
    allowedKeysForEvent !== undefined
    && !allowedKeysForEvent.test(event.key)
    && !specialKeysRegexp.test(event.key)
  ) {
    event.preventDefault();
  } else if (onKeyDown !== undefined) {
    onKeyDown(currentValue, event);
  }
};

const handlePaste = (event: ClipboardEvent): void => {
  const clipboardData = event.clipboardData as DataTransfer;
  // `selectionStart` and `selectionEnd` do not exist on inputs with type `number`, so we just
  // want to replace the entire content when pasting something in that case.
  const selectionStart = (event.target as HTMLInputElement).selectionStart || 0;
  const selectionEnd = (event.target as HTMLInputElement).selectionEnd || currentValue.length;
  const filteredValue = (globalAllowedKeys.default !== null)
    ? (clipboardData.getData('text').match(globalAllowedKeys.default as RegExp) || []).join('')
    : clipboardData.getData('text');
  handleChange({
    target: {
      value: `${currentValue.slice(0, selectionStart)}${filteredValue}${currentValue.slice(selectionEnd)}`,
      selectionStart: selectionStart + filteredValue.length,
    },
  } as unknown as InputEvent, false);
  event.preventDefault();
  if (onPaste !== undefined) {
    onPaste(currentValue, event);
  }
};

const handleBlur = (event: FocusEvent): void => {
  if (onBlur !== undefined) {
    onBlur(currentValue, event);
  }
};

const handleFocus = (event: FocusEvent): void => {
  if (onFocus !== undefined) {
    onFocus(currentValue, event);
  }
};

const handleIconClick = (event: MouseEvent): void => {
  if (onIconClick !== undefined) {
    onIconClick(event);
  }
};

const handleIconKeyDown = (event: KeyboardEvent): void => {
  if (onIconKeyDown !== undefined) {
    onIconKeyDown(event);
  }
};

// -------------------------------------------------------------------------------------------------
// PROPS REACTIVITY MANAGEMENT.
// -------------------------------------------------------------------------------------------------

// Updates current value whenever `value` and `transform` props change.
$: {
  // Do not update current value immediatly while user is typing something else.
  if (!userIsTyping) {
    const [newValue] = (transform as Transform)(value as string, 0);
    currentValue = newValue;
    updateCursorPosition();
  }
}
</script>

<!-- svelte-ignore a11y-autofocus -->
<div
id={id}
  class={className}
>
  {#if label !== undefined}
    <label for={randomId} class="ui-textfield__label">
      {@html markdown(label)}
    </label>
  {/if}
  <div class="ui-textfield__wrapper">
    {#if icon !== undefined && iconPosition === 'left'}
      <span
        tabIndex="0"
        role="button"
        class="ui-textfield__wrapper__icon"
        on:click={handleIconClick}
        on:keydown={handleIconKeyDown}
      >
        <UIIcon name={icon} />
      </span>
    {/if}
    <input
      max={max}
      min={min}
      name={name}
      step={step}
      size={size}
      type={type}
      id={randomId}
      readonly={readonly}
      bind:this={inputRef}
      on:blur={handleBlur}
      value={currentValue}
      maxlength={maxlength}
      autofocus={autofocus}
      disabled={isDisabled}
      on:focus={handleFocus}
      placeholder={placeholder}
      on:keydown={handleKeyDown}
      autocomplete={autocomplete}
      class="ui-textfield__wrapper__field"
      on:paste={(!readonly && !isDisabled) ? handlePaste : null}
      on:input={(!readonly && !isDisabled) ? handleChange : null}
    >
    {#if icon !== undefined && iconPosition === 'right'}
      <span
        tabIndex="0"
        role="button"
        class="ui-textfield__wrapper__icon"
        on:click={handleIconClick}
        on:keydown={handleIconKeyDown}
      >
        <UIIcon name={icon} />
      </span>
    {/if}
  </div>
  {#if helper !== undefined}
    <span  class="ui-textfield__helper">
      {@html markdown(helper)}
    </span>
  {/if}
</div>
