// library/src/scripts/vue/Tooltip.vue
<!-- Tooltip wrapper, for accessibility. -->
<script lang="ts" setup>
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import { computed, ref } from 'vue';
import buildClass from 'scripts/helpers/buildClass';

const props = defineProps<{
  label: string;
  modifiers?: string;
  description?: string;
}>();

const isDescriptionVisible = ref(false);

const displayDescription = () => {
  isDescriptionVisible.value = true;
};

const hideDescription = () => {
  isDescriptionVisible.value = false;
};

const className = computed(() => buildClass('ui-tooltip', [props.modifiers || '', isDescriptionVisible.value ? 'described' : ''].join(' ')));
</script>

<template>
  <div
    role="tooltip"
    :class="className"
    :aria-label="label"
    @focus="displayDescription"
    @focusout="hideDescription"
    @keypress="displayDescription"
  >
    <slot />
    <span
      v-if="isDescriptionVisible && description !== undefined"
      class="ui-tooltip__description"
      role="status"
    >{{ description }}</span>
  </div>
</template>

// library/src/scripts/svelte/Tooltip.svelte
<!-- Tooltip wrapper, for accessibility. -->
<script lang="ts">
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import buildClass from 'scripts/helpers/buildClass';

export let label: string;
export let modifiers = '';
export let id: string | undefined = undefined;
export let description: string | undefined = undefined;

let isDescriptionVisible = false;

const displayDescription = () => {
  isDescriptionVisible = true;
};

const hideDescription = () => {
  isDescriptionVisible = false;
};

$: className = buildClass('ui-tooltip', [modifiers, isDescriptionVisible ? 'described' : ''].join(' '));
</script>

<div
  {id}
  role="tooltip"
  class={className}
  aria-label={label}
  on:focus={displayDescription}
  on:focusout={hideDescription}
  on:keypress={displayDescription}
>
<slot></slot>
{#if isDescriptionVisible && description !== null}
  <span class="ui-tooltip__description" role="status">{description}</span>
{/if}
</div>
