// library/src/scripts/react/Tooltip.tsx
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import * as React from 'react';
import buildClass from 'scripts/helpers/buildClass';

/**
 * Tooltip wrapper, for accessibility.
 */
function Tooltip(props: UITooltipProps): JSX.Element {
  const { label, children } = props;
  let { id, description, modifiers } = props;

  id = id || null;
  modifiers = modifiers || 'top';
  description = description || null;

  const [isDescriptionVisible, setIsDescriptionVisible] = React.useState(false);
  const className = buildClass('ui-tooltip', [modifiers, isDescriptionVisible ? 'described' : ''].join(' '));

  const displayDescription = React.useCallback(() => {
    setIsDescriptionVisible(true);
  }, []);

  const hideDescription = React.useCallback(() => {
    setIsDescriptionVisible(false);
  }, []);

  return (
    <div
      id={id as string}
      role="tooltip"
      className={className}
      aria-label={label}
      onFocus={displayDescription}
      onKeyPress={displayDescription}
      onBlur={hideDescription}
    >
      {children}
      {(isDescriptionVisible && description !== undefined) && (
        <span className="ui-tooltip__description" role="status">{description}</span>
      )}
    </div>
  );
}

export default React.memo(Tooltip);

// library/src/scripts/svelte/Tooltip.svelte
<!-- Tooltip wrapper, for accessibility. -->
<script lang="ts">
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import buildClass from 'scripts/helpers/buildClass';

export let label: string;
export let modifiers = '';
export let id: string | undefined = undefined;
export let description: string | undefined = undefined;

let isDescriptionVisible = false;

const displayDescription = () => {
  isDescriptionVisible = true;
};

const hideDescription = () => {
  isDescriptionVisible = false;
};

$: className = buildClass('ui-tooltip', [modifiers, isDescriptionVisible ? 'described' : ''].join(' '));
</script>

<div
  {id}
  role="tooltip"
  class={className}
  aria-label={label}
  on:focus={displayDescription}
  on:focusout={hideDescription}
  on:keypress={displayDescription}
>
<slot></slot>
{#if isDescriptionVisible && description !== null}
  <span class="ui-tooltip__description" role="status">{description}</span>
{/if}
</div>
