// examples/svelte/src/scripts/pages/Buttons.svelte
<!-- Buttons page. -->
<script lang="ts" setup>
  /**
   * Copyright (c) Openizr. All Rights Reserved.
   *
   * This source code is licensed under the MIT license found in the
   * LICENSE file in the root directory of this source tree.
   *
   */

  import type { Locale } from 'basx/i18n';
  import { UIButton } from 'biuty/svelte';

  const { log } = console;

  const onClick = (): void => {
    log('Clicked!');
  };
  const onFocus = (): void => {
    log('Focused!');
  };

  export let locale: Locale;
</script>

<div class="vgap-5">
  <main class="grid cols-1 hgap-3 vgap-5">
    <a href="/" class="cols-l-3">GO BACK</a>
    {locale}
    <UIButton label="ui-button" />
    <UIButton label="ui-button icon left" icon="star" />
    <UIButton label="ui-button icon right" icon="star" iconPosition="right" />
    <UIButton label="ui-button disabled" modifiers="disabled" />
    <UIButton label="ui-button with listener" on:click={onClick} />
    <UIButton label="ui-button with type submit" type="submit" />
    <UIButton label="ui-button with focus listener" on:focus={onFocus} />
  </main>
</div>

// examples/vue/src/scripts/pages/Buttons.tsx
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import * as React from 'react';
import { UIButton } from 'biuty/react';

const onClick = (): void => {
  console.log('Clicked!');
};

const onFocus = (): void => {
  console.log('Focused!');
};

/**
 * Buttons page.
 */
export default function Buttons(): JSX.Element {
  return (
    <div>
      <main className="grid cols-1 hgap-3 vgap-5">
        <a href="/">GO BACK</a>
        <UIButton label="ui-button" />
        <UIButton label="ui-button icon left" icon="star" />
        <UIButton label="ui-button icon right" icon="star" iconPosition="right" />
        <UIButton label="ui-button disabled" modifiers="disabled" />
        <UIButton label="ui-button with listener" onClick={onClick} />
        <UIButton label="ui-button with type submit" type="submit" />
        <UIButton label="ui-button with focus listener" onFocus={onFocus} />
        <UIButton icon="star" onFocus={onFocus} />
      </main>
    </div>
  );
}

Buttons.displayName = 'Buttons';
