// library/src/sonar-ui/react/FileUploader.tsx
/**
 * Copyright (c) Matthieu Jabbour. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import * as React from 'react';
import PropTypes, { InferProps } from 'prop-types';
import buildClass from 'sonar-ui/helpers/buildClass';
import generateRandomId from 'sonar-ui/helpers/generateRandomId';

const propTypes = {
  id: PropTypes.string,
  icon: PropTypes.string,
  label: PropTypes.string,
  onFocus: PropTypes.func,
  helper: PropTypes.string,
  onChange: PropTypes.func,
  multiple: PropTypes.bool,
  modifiers: PropTypes.string,
  placeholder: PropTypes.string,
  name: PropTypes.string.isRequired,
  iconPosition: PropTypes.oneOf(['left', 'right']),
};

const defaultProps = {
  id: null,
  icon: null,
  label: null,
  helper: null,
  onFocus: null,
  modifiers: '',
  multiple: false,
  placeholder: null,
  iconPosition: 'left',
  onChange: (): null => null,
};

/**
 * File uploader.
 */
export default function UIFileUploader(props: InferProps<typeof propTypes>): JSX.Element {
  const {
    id, modifiers, label, helper, iconPosition, icon,
    onChange, multiple, name, placeholder, onFocus,
  } = props;
  const [randomId] = React.useState(generateRandomId);
  const [currentValue, setCurrentValue] = React.useState([] as string[]);
  const className = buildClass('ui-file-uploader', (modifiers as string).split(' '));

  const changeValue = (event: React.ChangeEvent<HTMLInputElement>): void => {
    const files = [];
    const numberOfFiles = (event.target.files?.length || 0);
    for (let index = 0; index < numberOfFiles; index += 1) {
      files.push((event.target.files as FileList)[index]);
    }
    setCurrentValue(files.map((file) => file.name));
    if (onChange !== undefined && onChange !== null) {
      onChange(files);
    }
  };

  const focusField = (): void => {
    if (onFocus !== undefined && onFocus !== null) {
      onFocus();
    }
  };

  const children = [
    (icon !== null) ? <i key="icon" className="ui-button__icon">{icon}</i> : null,
    <input
      type="file"
      name={name}
      id={randomId}
      key={randomId}
      onFocus={focusField}
      onChange={changeValue}
      multiple={multiple as boolean}
      className="ui-file-uploader__field"
    />,
  ];
  return (
    <div
      id={id as string}
      className={className}
    >
      {(label !== null)
        ? <label className="ui-file-uploader__label" htmlFor={randomId}>{label}</label>
        : null}
      {(iconPosition === 'left') ? children : children.reverse()}
      <span className="ui-file-uploader__files-list">{(currentValue.length === 0) ? placeholder : currentValue.join(', ')}</span>
      {(helper !== null) ? <p className="ui-file-uploader__helper">{helper}</p> : null}
    </div>
  );
}

UIFileUploader.propTypes = propTypes;
UIFileUploader.defaultProps = defaultProps;
UIFileUploader.displayName = 'UIFileUploader';

// library/src/scripts/vue/FileUploader.vue
<template>
  <div
    :id="id"
    :class="className"
  >
    <label
      v-if="label !== null"
      class="ui-file-uploader__label"
      :for="randomId"
    >{{ label }}</label>
    <i
      v-if="icon !== null && iconPosition === 'left'"
      class="ui-button__icon"
    >{{ icon }}</i>
    <input
      :id="randomId"
      type="file"
      :name="name"
      :multiple="multiple"
      class="ui-file-uploader__field"
      @focus="focusField"
      @change="changeField"
    >
    <i
      v-if="icon !== null && iconPosition === 'right'"
      class="ui-button__icon"
    >{{ icon }}</i>
    <span class="ui-file-uploader__files-list">
      {{ (currentValue.length === 0) ? placeholder : currentValue.join(', ') }}
    </span>
    <p
      v-if="helper !== null"
      class="ui-file-uploader__helper"
    >
      {{ helper }}
    </p>
  </div>
</template>

<script lang="ts">
/**
 * Copyright (c) Matthieu Jabbour. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import Vue from 'vue';
import { Generic } from 'scripts/types';
import buildClass from 'scripts/helpers/buildClass';
import generateRandomId from 'scripts/helpers/generateRandomId';

interface Props {
  id: string;
  name: string;
  icon: string;
  label: string;
  helper: string;
  modifiers: string;
  multiple: boolean;
  placeholder: string;
  iconPosition: 'left' | 'right';
}

/**
 * File uploader.
 */
export default Vue.extend<Generic, Generic, Generic, Props>({
  name: 'UIFileUploader',
  props: {
    id: {
      type: String,
      default: null,
      required: false,
    },
    icon: {
      type: String,
      default: null,
      required: false,
    },
    name: {
      type: String,
      required: true,
    },
    label: {
      type: String,
      default: null,
      required: false,
    },
    helper: {
      type: String,
      default: null,
      required: false,
    },
    placeholder: {
      type: String,
      default: null,
      required: false,
    },
    modifiers: {
      type: String,
      default: '',
      required: false,
    },
    iconPosition: {
      validator: (value) => value === 'left' || value === 'right',
      default: 'left',
      required: false,
    },
    multiple: {
      type: Boolean,
      default: false,
      required: false,
    },
  },
  data() {
    return {
      randomId: generateRandomId(),
      currentValue: [],
    };
  },
  computed: {
    className(): string {
      return buildClass('ui-file-uploader', this.modifiers.split(' '));
    },
  },
  methods: {
    changeField(event: Event): void {
      const files = [];
      const numberOfFiles = ((event.target as HTMLInputElement).files?.length || 0);
      for (let index = 0; index < numberOfFiles; index += 1) {
        files.push(((event.target as HTMLInputElement).files as FileList)[index]);
      }
      this.currentValue = files.map((file) => file.name);
      this.$emit('change', files);
    },
    focusField(): void {
      this.$emit('focus', this.currentValue);
    },
  },
});
</script>
