// library/src/sonar-ui/react/Textfield.tsx
/**
 * Copyright (c) Matthieu Jabbour. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import * as React from 'react';
import PropTypes, { InferProps } from 'prop-types';
import buildClass from 'sonar-ui/helpers/buildClass';
import generateRandomId from 'sonar-ui/helpers/generateRandomId';

const propTypes = {
  id: PropTypes.string,
  min: PropTypes.number,
  max: PropTypes.number,
  step: PropTypes.number,
  onBlur: PropTypes.func,
  icon: PropTypes.string,
  size: PropTypes.number,
  onFocus: PropTypes.func,
  value: PropTypes.string,
  label: PropTypes.string,
  helper: PropTypes.string,
  onChange: PropTypes.func,
  readonly: PropTypes.bool,
  maxlength: PropTypes.number,
  modifiers: PropTypes.string,
  onIconClick: PropTypes.func,
  placeholder: PropTypes.string,
  name: PropTypes.string.isRequired,
  iconPosition: PropTypes.oneOf(['left', 'right']),
  type: PropTypes.oneOf(['text', 'email', 'number', 'password', 'search', 'tel', 'url']),
};

const defaultProps = {
  id: null,
  min: null,
  max: null,
  step: null,
  size: null,
  icon: null,
  value: '',
  label: null,
  helper: null,
  type: 'text',
  modifiers: '',
  onBlur: null,
  onFocus: null,
  onChange: null,
  readonly: false,
  maxlength: null,
  placeholder: null,
  iconPosition: 'left',
  onIconClick: undefined,
};

/**
 * Textfield.
 */
export default function UITextfield(props: InferProps<typeof propTypes>): JSX.Element {
  const {
    id, modifiers, label, helper, onChange, value, name, readonly, step, onIconClick,
    placeholder, iconPosition, icon, onBlur, type, size, max, min, maxlength, onFocus,
  } = props;
  const [randomId] = React.useState(generateRandomId);
  const [currentValue, setCurrentValue] = React.useState(value);
  const className = buildClass('ui-textfield', (modifiers as string).split(' '));

  // Updates current value each time the `value` property is changed.
  React.useEffect(() => {
    setCurrentValue(value);
  }, [value]);

  const changeValue = (event: React.ChangeEvent<HTMLInputElement>): void => {
    setCurrentValue(event.target.value);
    if (onChange !== undefined && onChange !== null) {
      onChange(event.target.value);
    }
  };

  const blurField = (event: React.ChangeEvent<HTMLInputElement>): void => {
    if (onBlur !== undefined && onBlur !== null) {
      onBlur(event.target.value);
    }
  };

  const focusField = (): void => {
    if (onFocus !== undefined && onFocus !== null) {
      onFocus();
    }
  };

  const children = [
    (icon !== null)
      // eslint-disable-next-line jsx-a11y/click-events-have-key-events
      ? <i key="icon" role="button" tabIndex={0} className="ui-textfield__wrapper__icon" onClick={onIconClick || undefined}>{icon}</i>
      : null,
    <input
      key="input"
      name={name}
      id={randomId}
      onBlur={blurField}
      onFocus={focusField}
      max={max as number}
      min={min as number}
      step={step as number}
      type={type as string}
      size={size as number}
      value={currentValue as string}
      readOnly={readonly as boolean}
      maxLength={maxlength as number}
      className="ui-textfield__wrapper__field"
      placeholder={placeholder as string}
      onChange={(readonly === false) ? changeValue : undefined}
      tabIndex={((modifiers as string).includes('disabled') ? -1 : 0)}
    />,
  ];

  return (
    <div
      id={id as string}
      className={className}
    >
      {(label !== null) ? <label className="ui-textfield__label" htmlFor={randomId}>{label}</label> : null}
      <div className="ui-textfield__wrapper">
        {(iconPosition === 'left') ? children : children.reverse()}
      </div>
      {(helper !== null) ? <span className="ui-textfield__helper">{helper}</span> : null}
    </div>
  );
}

UITextfield.propTypes = propTypes;
UITextfield.defaultProps = defaultProps;
UITextfield.displayName = 'UITextfield';

// library/src/scripts/vue/Textfield.vue
<template>
  <!-- eslint-disable vue/no-v-html -->
  <div
    :id="id"
    :class="className"
  >
    <label
      v-if="label !== null"
      class="ui-textfield__label"
      :for="randomId"
      v-html="markdown(label)"
    />
    <div class="ui-textfield__wrapper">
      <i
        v-if="icon !== null && iconPosition === 'left'"
        role="button"
        tabIndex="0"
        class="ui-textfield__wrapper__icon"
        @click="clickIcon"
      >{{ icon }}</i>
      <input
        :id="randomId"
        v-model="currentValue"
        :name="name"
        :max="max"
        :min="min"
        :step="step"
        :type="type"
        :size="size"
        :value="currentValue"
        :readonly="readonly"
        :maxlength="maxlength"
        class="ui-textfield__wrapper__field"
        :placeholder="placeholder"
        :autocomplete="autocomplete"
        :disabled="modifiers.includes('disabled')"
        @input="changeField"
        @blur="blurField"
        @focus="focusField"
      >
      <i
        v-if="icon !== null && iconPosition === 'right'"
        role="button"
        tabIndex="0"
        class="ui-textfield__wrapper__icon"
        @click="clickIcon"
      >{{ icon }}</i>
    </div>
    <span
      v-if="helper !== null"
      class="ui-textfield__helper"
    >{{ helper }}</span>
  </div>
</template>

<script lang="ts">
/**
 * Copyright (c) Matthieu Jabbour. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import Vue from 'vue';
import { Generic } from 'scripts/types';
import markdown from 'scripts/helpers/markdown';
import buildClass from 'scripts/helpers/buildClass';
import generateRandomId from 'scripts/helpers/generateRandomId';

interface Props {
  name: string;
  value: string;
  min: number;
  max: number;
  step: number;
  size: number;
  icon: string;
  id: string;
  label: string;
  helper: string;
  maxlength: number;
  modifiers: string;
  readonly: boolean;
  placeholder: string;
  autocomplete: string;
  iconPosition: 'left' | 'right';
  type: 'text' | 'email' | 'number' | 'password' | 'search' | 'tel' | 'url';
}

/**
 * Textfield.
 */
export default Vue.extend<Generic, Generic, Generic, Props>({
  name: 'UITextfield',
  props: {
    id: {
      type: String,
      default: null,
      required: false,
    },
    name: {
      type: String,
      required: true,
    },
    min: {
      type: Number,
      default: null,
      required: false,
    },
    max: {
      type: Number,
      default: null,
      required: false,
    },
    step: {
      type: Number,
      default: null,
      required: false,
    },
    size: {
      type: Number,
      default: null,
      required: false,
    },
    maxlength: {
      type: Number,
      default: null,
      required: false,
    },
    icon: {
      type: String,
      default: null,
      required: false,
    },
    value: {
      type: String,
      default: '',
      required: false,
    },
    label: {
      type: String,
      default: null,
      required: false,
    },
    helper: {
      type: String,
      default: null,
      required: false,
    },
    placeholder: {
      type: String,
      default: null,
      required: false,
    },
    readonly: {
      type: Boolean,
      default: false,
      required: false,
    },
    modifiers: {
      type: String,
      default: '',
      required: false,
    },
    iconPosition: {
      validator: (value) => value === 'left' || value === 'right',
      default: 'left',
      required: false,
    },
    type: {
      validator: (value) => ['text', 'email', 'number', 'password', 'search', 'tel', 'url'].includes(value),
      default: 'text',
      required: false,
    },
    autocomplete: {
      type: String,
      default: 'on',
      required: false,
    },
  },
  data() {
    return {
      randomId: generateRandomId(),
      currentValue: this.value,
    };
  },
  computed: {
    className(): string {
      return buildClass('ui-textfield', this.modifiers.split(' '));
    },
  },
  watch: {
    value(): void {
      // Updates current value each time the `value` property is changed.
      this.currentValue = this.value;
    },
  },
  methods: {
    changeField(event: KeyboardEvent): void {
      this.$emit('change', (event.target as HTMLInputElement).value);
    },
    blurField(): void {
      this.$emit('blur', this.currentValue as string);
    },
    focusField(): void {
      this.$emit('focus', this.currentValue as string);
    },
    clickIcon(): void {
      this.$emit('iconClick');
    },
    markdown(label: string): string {
      return markdown(label);
    },
  },
});
</script>
