// library/src/scripts/svelte/FilePicker.svelte
<!-- File picker. -->
<script lang="ts">
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import UIIcon from 'scripts/svelte/Icon.svelte';
import markdown from 'scripts/helpers/markdown';
import buildClass from 'scripts/helpers/buildClass';
import generateRandomId from 'scripts/helpers/generateRandomId';

const toArray = (newValue: File | File[]): File[] => (Array.isArray(newValue)
  ? newValue
  : [newValue]);

export let name: string;
export let modifiers = '';
export let multiple = false;
export let value: File | File[] = [];
export let id: string | undefined = undefined;
export let icon: string | undefined = undefined;
export let label: string | undefined = undefined;
export let accept: string | undefined = undefined;
export let helper: string | undefined = undefined;
export let iconPosition: 'left' | 'right' = 'left';
export let placeholder: string | undefined = undefined;
export let onChange: ((value: File | File[], event: InputEvent) => void) | undefined = undefined;
export let onFocus: ((value: File | File[], event: FocusEvent) => void) | undefined = undefined;
export let onBlur: ((value: File | File[], event: FocusEvent) => void) | undefined = undefined;

let currentValue = toArray(value);
const randomId = generateRandomId();

$: className = buildClass('ui-file-picker', modifiers + (multiple ? ' multiple' : ''));
$: currentPlaceholder = (currentValue.length > 0) ? currentValue.map((file) => file.name).join(', ') : placeholder;

// -----------------------------------------------------------------------------------------------
// CALLBACKS DECLARATION.
// -----------------------------------------------------------------------------------------------

const handleChange = (event: Event): void => {
  const files = [];
  const target = event.target as HTMLInputElement;
  const numberOfFiles = (target.files as FileList).length;
  for (let index = 0; index < numberOfFiles; index += 1) {
    files.push((target.files as FileList)[index]);
  }
  currentValue = files;
  if (onChange !== undefined) {
    onChange(multiple ? files : files[0], event as InputEvent);
  }
};

const handleFocus = (event: FocusEvent): void => {
  if (onFocus !== undefined) {
    onFocus(multiple ? currentValue : currentValue[0], event);
  }
};

const handleBlur = (event: FocusEvent): void => {
  if (onBlur !== undefined) {
    onBlur(multiple ? currentValue : currentValue[0], event);
  }
};

// -------------------------------------------------------------------------------------------------
// PROPS REACTIVITY MANAGEMENT.
// -------------------------------------------------------------------------------------------------

// Updates current value whenever `value` prop changes.
const updateValue = (updatedValue: File | File[]) => {
  currentValue = toArray(updatedValue);
};
$: updateValue(value);
</script>

<div
  id={id}
  class={className}
>
  {#if label !== undefined}
    <label for={randomId} class="ui-file-picker__label">
      {@html markdown(label)}
    </label>
  {/if}
  <div class="ui-file-picker__wrapper">
    {#if icon !== undefined && iconPosition === 'left'}
      <UIIcon name={icon} />
    {/if}
    <input
      type="file"
      name={name}
      id={randomId}
      accept={accept}
      multiple={multiple}
      on:blur={handleBlur}
      on:focus={handleFocus}
      on:input={handleChange}
      class="ui-file-picker__wrapper__field"
      tabIndex={modifiers.includes('disabled') ? -1 : 0}
    >
    {#if icon !== undefined && iconPosition === 'right'}
      <UIIcon name={icon} />
    {/if}
    <span class="ui-file-picker__wrapper__placeholder">
      {currentPlaceholder}
    </span>
  </div>
  {#if helper !== undefined}
    <span  class="ui-file-picker__helper">
      {@html markdown(helper)}
    </span>
  {/if}
</div>

// library/src/scripts/react/FilePicker.tsx
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import * as React from 'react';
import UIIcon from 'scripts/react/Icon';
import markdown from 'scripts/helpers/markdown';
import buildClass from 'scripts/helpers/buildClass';
import generateRandomId from 'scripts/helpers/generateRandomId';

const JSXUIIcon = UIIcon as JSXElement;

const defaultValue: File[] = [];
const toArray = (value: File | File[]): File[] => (Array.isArray(value) ? value : [value]);

/**
 * File picker.
 */
function UIFilePicker(props: UIFilePickerProps): JSX.Element {
  const { name } = props;
  const { placeholder } = props;
  const { icon, onChange, multiple } = props;
  const { accept, id, modifiers = '' } = props;
  const { label, helper, iconPosition = 'left' } = props;
  const { value = defaultValue, onBlur, onFocus } = props;

  const [randomId] = React.useState(generateRandomId);
  const [currentValue, setCurrentValue] = React.useState<File[]>(toArray(value));
  const className = buildClass('ui-file-picker', `${modifiers}${(multiple ? ' multiple' : '')}`);

  // -----------------------------------------------------------------------------------------------
  // CALLBACKS DECLARATION.
  // -----------------------------------------------------------------------------------------------

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>): void => {
    const files = [];
    const numberOfFiles = ((event.target.files as FileList).length);
    for (let index = 0; index < numberOfFiles; index += 1) {
      files.push((event.target.files as FileList)[index]);
    }
    setCurrentValue(files);
    if (onChange !== undefined) {
      onChange(multiple ? files : files[0], event as unknown as InputEvent);
    }
  };

  const handleFocus = (event: React.FocusEvent<HTMLInputElement>): void => {
    if (onFocus !== undefined) {
      onFocus(multiple ? currentValue : currentValue[0], event as unknown as FocusEvent);
    }
  };

  const handleBlur = (event: React.FocusEvent<HTMLInputElement>): void => {
    if (onBlur !== undefined) {
      onBlur(multiple ? currentValue : currentValue[0], event as unknown as FocusEvent);
    }
  };

  // -----------------------------------------------------------------------------------------------
  // PROPS REACTIVITY MANAGEMENT.
  // -----------------------------------------------------------------------------------------------

  // Updates current value whenever `value` prop changes.
  React.useEffect(() => {
    setCurrentValue(toArray(value));
  }, [value]);

  // -----------------------------------------------------------------------------------------------
  // COMPONENT RENDERING.
  // -----------------------------------------------------------------------------------------------

  const children = [
    (icon !== undefined) ? <JSXUIIcon key="icon" name={icon} /> : null,
    <input
      key="file"
      type="file"
      name={name}
      id={randomId}
      accept={accept}
      multiple={multiple}
      onBlur={handleBlur}
      onFocus={handleFocus}
      onChange={handleChange}
      className="ui-file-picker__wrapper__field"
      tabIndex={modifiers.includes('disabled') ? -1 : 0}
    />,
  ];
  return (
    <div
      id={id}
      className={className}
    >
      {(label !== undefined) && (
        <label
          className="ui-file-picker__label"
          htmlFor={randomId}
          dangerouslySetInnerHTML={{ __html: markdown(label) }}
        />
      )}
      <div className="ui-file-picker__wrapper">
        {(iconPosition === 'left') ? children : children.reverse()}
        <span className="ui-file-picker__wrapper__placeholder">
          {(currentValue.length === 0) ? placeholder : currentValue.map((file) => file.name).join(', ')}
        </span>
      </div>
      {(helper !== undefined) && (
        <span
          className="ui-file-picker__helper"
          dangerouslySetInnerHTML={{ __html: markdown(helper) }}
        />
      )}
    </div>
  );
}

export default React.memo(UIFilePicker);
