// library/src/scripts/svelte/Options.svelte
<!-- Set of selectable options. -->
<script lang="ts">
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import markdown from 'scripts/helpers/markdown';
import buildClass from 'scripts/helpers/buildClass';
import generateRandomId from 'scripts/helpers/generateRandomId';

type ChangeEventHandler = (value: string | string[], event: InputEvent) => void;

const toArray = (value: string | string[]): string[] => (Array.isArray(value) ? value : [value]);

export let name: string;
export let modifiers = '';
export let select = false;
export let multiple = false;
export let options: Option[];
export let value: string | string[] = [];
export let id: string | undefined = undefined;
export let label: string | undefined = undefined;
export let helper: string | undefined = undefined;
export let disabled: boolean | undefined = false;
export let selectPosition: 'top' | 'bottom' | undefined = undefined;
export let onFocus: ((value: string, event: FocusEvent) => void) | undefined = undefined;
export let onChange: ChangeEventHandler | undefined = undefined;

let mounted = false;
let isFocused = false;
let position = 'bottom';
let isDisplayed = false;
let focusedOptionIndex = -1;
let currentValue = toArray(value);
const randomId = generateRandomId();
let buttonRef: HTMLElement | null = null;
let wrapperRef: HTMLElement | null = null;

$: className = buildClass(
  'ui-options',
  `${modifiers}${select ? ' select' : ''}${multiple ? ' multiple' : ''}${disabled ? ' disabled' : ''}`,
);
// Memoizes all options' parsed labels to optimize rendering.
$: optionParsedLabels = options.reduce((mapping, option, index) => {
  if (option.type === 'option') {
    return { ...mapping, [option.value]: markdown(option.label) };
  }
  if (option.type === 'header') {
    return { ...mapping, [`header_${index}`]: markdown(option.label) };
  }
  return mapping;
}, {} as Record<string, string>);

// -----------------------------------------------------------------------------------------------
// CALLBACKS DECLARATION.
// -----------------------------------------------------------------------------------------------

// Updates the `isFocused` ref when blurring options.
const handleBlur = (): void => {
  isFocused = false;
};

// In `select` mode only, displays the options list at the right place on the viewport.
const displayList = (): void => {
  if (buttonRef !== null && !disabled) {
    if (selectPosition !== undefined) {
      position = selectPosition;
    } else {
      const relativeOffsetTop = buttonRef.getBoundingClientRect().top;
      position = relativeOffsetTop > window.innerHeight / 2 ? 'top' : 'bottom';
    }
    isDisplayed = true;
  }
};

// In `select` mode only, hides the options list only if forced or if focus is lost.
const hideList = (force = false) => (event: FocusEvent | null): void => {
  // We first ensure that the newly focused element is not an option of the list.
  const focusIsOutsideList = event !== null && wrapperRef !== null
    ? !wrapperRef.contains(event.relatedTarget as Node)
    : true;
  if (focusIsOutsideList && (force === true || !multiple)) {
    handleBlur();
    isDisplayed = false;
  }
};

// Finds the direct previous or next option when navigating with keyboard.
const findSiblingOption = (
  startIndex: number,
  direction: number,
  offset = 1,
): number => {
  const nextIndex = startIndex + direction * offset;
  if (nextIndex < 0 || nextIndex >= options.length) {
    return startIndex;
  }
  const option = options[nextIndex];
  return option.type === 'option' && !option.disabled
    ? nextIndex
    : findSiblingOption(startIndex, direction, offset + 1);
};

// Automatically triggered when a `focus` event is fired.
const handleFocus = (optionValue: string, optionIndex: number) => (event: FocusEvent): void => {
  if (!disabled) {
    isFocused = true;
    focusedOptionIndex = optionIndex;
    if (onFocus !== undefined) {
      onFocus(optionValue, event);
    }
  }
};

// Manually triggered, used to simulate `focus` events (`select` mode).
const focusOption = (optionIndex: number): void => {
  const refNode = wrapperRef;
  if (
    refNode !== null
    && optionIndex < refNode.childNodes.length
    && optionIndex >= 0
  ) {
    (refNode.childNodes[optionIndex] as HTMLElement).focus();
  }
};

// Automatically triggered when a `change` event is fired.
const handleChange = (event: Event): void => {
  if (!disabled) {
    const target = (event.target as HTMLInputElement);
    const selectedIndex = currentValue.indexOf(target.value);
    let newValue = [target.value];
    if (multiple === true) {
      newValue = selectedIndex >= 0
        ? currentValue
          .slice(0, selectedIndex)
          .concat(currentValue.slice(selectedIndex + 1))
        : currentValue.concat([target.value]);
    }
    // If the value hasn't changed, we don't trigger anything.
    if (multiple || newValue[0] !== currentValue[0]) {
      currentValue = newValue;
      if (onChange !== undefined) {
        onChange(multiple === true ? newValue : newValue[0], event as InputEvent);
      }
    }
  }
};

// Manually triggered, used to simulate `change` events (`select` mode).
const changeOption = (optionIndex: number) => (): void => {
  if (!disabled) {
    focusedOptionIndex = optionIndex;
    const optionValue = (options[optionIndex] as UIOptionsOption).value;
    handleChange({ target: { value: optionValue } } as unknown as InputEvent);
    if (select === true) {
      hideList()(null);
    }
  }
};

// -----------------------------------------------------------------------------------------------
// KEYBOARD NAVIGATION.
// -----------------------------------------------------------------------------------------------

// Handles keyboard navigation amongst options.
const handleKeydown = (event: KeyboardEvent): void => {
  if (!disabled) {
    const { key } = event;
    const navigationControls: Record<string, () => number> = {
      ArrowUp: () => findSiblingOption(focusedOptionIndex, -1),
      ArrowLeft: () => findSiblingOption(focusedOptionIndex, -1),
      ArrowDown: () => findSiblingOption(focusedOptionIndex, +1),
      ArrowRight: () => findSiblingOption(focusedOptionIndex, +1),
      PageUp: () => Math.max(0, findSiblingOption(-1, +1)),
      Home: () => Math.max(0, findSiblingOption(-1, +1)),
      PageDown: () => Math.min(options.length - 1, findSiblingOption(options.length, -1)),
      End: () => Math.min(options.length - 1, findSiblingOption(options.length, -1)),
    };

    const siblingOption = navigationControls[key];
    if (siblingOption !== undefined) {
      // User is navigating through options...
      if (isDisplayed || !select) {
        focusOption(siblingOption());
      } else {
        changeOption(siblingOption())();
      }
      // `event.preventDefault` is not called globally to avoid overriding `Tab` behaviour.
      event.preventDefault();
    } else if (key === ' ' || key === 'Enter') {
      // User wants to select / unselect an option...
      if (!isDisplayed && select) {
        isDisplayed = true;
      } else {
        changeOption(focusedOptionIndex)();
      }
      event.preventDefault();
    } else if (key === 'Escape') {
      // User wants to hide list (`select` mode)...
      hideList(true)(null);
      event.preventDefault();
    }
  }
};

// -----------------------------------------------------------------------------------------------
// PROPS REACTIVITY MANAGEMENT.
// -----------------------------------------------------------------------------------------------

// Updates `firstSelectedOption` ref whenever `currentValue` changes.
let firstSelectedOption = -1;
$: {
  if (currentValue.length === 0) {
    firstSelectedOption = findSiblingOption(-1, 1);
  }
  firstSelectedOption = Math.max(
    0,
    options.findIndex((option) => option.type === 'option' && currentValue.includes(option.value)),
  );
}

// Updates current value whenever `value` property changes.
$: currentValue = toArray(value);

// Updates current value whenever `multiple` property changes.
const updateCurrentValue = (newMultiple: boolean) => {
  currentValue = (newMultiple || currentValue.length === 0)
    ? currentValue
    : [currentValue[0]];
};
$: updateCurrentValue(multiple);

// Re-focuses the right option whenever `options` property changes, to avoid out of range focus.
const updateFocus = (newOptions: Option[]): void => {
  if (isFocused && newOptions) {
    focusOption(firstSelectedOption);
  }
};
$: updateFocus(options);

// HTML elements with `display: none` can't be focused. Thus, we need to wait for the HTML list to
// be displayed before actually focusing it (`select` mode).
const updateSelectFocus = (newMounted: boolean, newIsDisplayed: boolean): void => {
  if (newMounted) {
    setTimeout(() => {
      if (wrapperRef !== undefined && select && newIsDisplayed) {
        focusOption(firstSelectedOption);
      } else if (!newIsDisplayed && buttonRef !== null) {
        buttonRef.focus();
      }
    }, 10);
  }
  mounted = true;
};
$: updateSelectFocus(mounted, isDisplayed);
$: onlyOptions = options.filter((option) => option.type === 'option') as UIOptionsOption[];
</script>

{#if select === true}
  <div {id} class={className}>
    {#if label !== undefined}
      <label for={randomId} class="ui-options__label">
        {@html markdown(label)}
      </label>
    {/if}
    <div class="ui-options__wrapper">
      <button
        id={randomId}
        bind:this={buttonRef}
        {name}
        type="button"
        aria-haspopup="listbox"
        tabindex={disabled ? -1 : 0}
        class="ui-options__wrapper__button"
        aria-labelledby={`${randomId} ${randomId}`}
        on:keydown={handleKeydown}
        on:mousedown={displayList}
        on:focus={handleFocus('', firstSelectedOption)}
      >
        {@html currentValue.map((optionValue) => optionParsedLabels[optionValue]).join(', ')}
      </button>
      <svelte:element
        this={"ul"}
        bind:this={wrapperRef}
        tabindex="-1"
        role="listbox"
        aria-labelledby={randomId}
        aria-expanded={isDisplayed}
        aria-multiselectable={multiple}
        aria-activedescendant={`${randomId}${focusedOptionIndex}`}
        class={buildClass('ui-options__wrapper__list', isDisplayed ? `${position} expanded` : position)}
        on:keydown={handleKeydown}
      >
        {#each options as option, index (`${randomId}${index}`)}
          <li
            id={`${randomId}${index}`}
            tabindex="-1"
            role={option.type === 'option' ? 'option' : undefined}
            aria-selected={option.type === 'option' && currentValue.includes(option.value)}
            class={buildClass(
              `ui-options__wrapper__list__${option.type}`,
              `${option.modifiers ?? ''}${option.type === 'option' && option.disabled
                ? ' disabled' : ''}${(option.type === 'option' && currentValue.includes(option.value)) ? ' checked' : ''}`,
            )}
            on:blur={hideList(true)}
            on:mousedown={(option.type === 'option' && !option.disabled) ? changeOption(index) : undefined}
            on:focus={(option.type === 'option' && !option.disabled) ? handleFocus(option.value, index) : undefined}
          >
            {@html option.type === 'divider' ? '' : optionParsedLabels[option.type === 'option' ? option.value : `header_${index}`]}
          </li>
        {/each}
      </svelte:element>
    </div>
    {#if helper !== undefined}
      <span class="ui-options__helper">
        {@html markdown(helper)}
      </span>
    {/if}
  </div>
{:else}
  <div {id} class={className}>
    {#if label !== undefined}
      <label for={`${randomId}_${Math.max(firstSelectedOption, 0)}`} class="ui-options__label">
        {@html markdown(label)}
      </label>
    {/if}
    <div bind:this={wrapperRef} class="ui-options__wrapper">
      {#each onlyOptions as option, index (`${randomId}${index}`)}
        <label
          class={buildClass(
            'ui-options__wrapper__option',
            `${option.modifiers ?? ''}${option.disabled
                ? ' disabled' : ''}${currentValue.includes(option.value) ? ' checked' : ''}`,
          )}
        >
          <input
            id={`${randomId}_${index}`}
            {name}
            checked={currentValue.includes(option.value)}
            type={multiple ? 'checkbox' : 'radio'}
            value={option.value}
            disabled={option.disabled}
            class="ui-options__wrapper__option__field"
            on:blur={handleBlur}
            on:change={handleChange}
            on:keydown={handleKeydown}
            on:focus={handleFocus(option.value, index)}
            tabindex={(
              option.disabled
              || disabled
              || !(((index === 0 || !multiple) && currentValue.length === 0)
              || option.value === currentValue[0]) ? -1 : 0
            )}
          />
          <span class="ui-options__wrapper__option__label">
            {@html optionParsedLabels[option.value]}
          </span>
        </label>
      {/each}
    </div>
    {#if helper !== undefined}
      <span class="ui-options__helper">
        {@html markdown(helper)}
      </span>
    {/if}
  </div>
{/if}

// library/src/scripts/react/Options.tsx
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import * as React from 'react';
import markdown from 'scripts/helpers/markdown';
import buildClass from 'scripts/helpers/buildClass';
import generateRandomId from 'scripts/helpers/generateRandomId';

const toArray = (value: string | string[]): string[] => (Array.isArray(value) ? value : [value]);

const defaultValue: string[] = [];

/**
 * Set of selectable options.
 */
function UIOptions(props: UIOptionsProps & {
  /** `focus` event handler. */
  onFocus?: React.FocusEventHandler<HTMLElement>;

  /** `change` event handler. */
  onChange?: React.ChangeEventHandler<HTMLElement>;
}): JSX.Element {
  const { options, name } = props;
  const { selectPosition } = props;
  const { id, modifiers = '', label } = props;
  const { multiple, select, onFocus } = props;
  const { helper, value = defaultValue, onChange } = props;

  const mounted = React.useRef(false);
  const wrapperRef = React.useRef(null);
  const isFocused = React.useRef(false);
  const firstSelectedOption = React.useRef(-1);
  const [randomId] = React.useState(generateRandomId);
  const buttonRef = React.useRef<HTMLButtonElement>(null);
  const [isDisplayed, setIsDisplayed] = React.useState(false);
  const [focusedOptionIndex, setFocusedOptionIndex] = React.useState(-1);
  const [position, setPosition] = React.useState(selectPosition ?? 'bottom');
  const [currentValue, setCurrentValue] = React.useState<string[]>(toArray(value));
  const className = buildClass('ui-options', `${modifiers} ${(select ? 'select' : '')} ${(multiple ? ' multiple' : '')}`);
  // Memoizes all options' parsed labels to optimize rendering.
  const optionParsedLabels = React.useMemo(() => options.reduce((mapping, option, index) => {
    if (option.type === 'option') {
      return { ...mapping, [option.value]: markdown(option.label) };
    }
    if (option.type === 'header') {
      return { ...mapping, [`header_${index}`]: markdown(option.label) };
    }
    return mapping;
  }, {} as Record<string, string>), [options]);

  // -----------------------------------------------------------------------------------------------
  // CALLBACKS DECLARATION.
  // -----------------------------------------------------------------------------------------------

  // Updates the `isFocused` ref when blurring options.
  const handleBlur = React.useCallback(() => {
    isFocused.current = false;
  }, []);

  // In `select` mode only, displays the options list at the right place on the viewport.
  const displayList = React.useCallback((): void => {
    if (selectPosition !== undefined) {
      setPosition(selectPosition);
    } else {
      const relativeOffsetTop = (buttonRef.current as HTMLInputElement).getBoundingClientRect().top;
      setPosition((relativeOffsetTop > window.innerHeight / 2) ? 'top' : 'bottom');
    }
    setIsDisplayed(true);
  }, [selectPosition]);

  // In `select` mode only, hides the options list only if forced or if focus is lost.
  const hideList = React.useCallback(
    (force = false) => (event: React.FocusEvent<HTMLElement> | null): void => {
      // We first ensure that the newly focused element is not an option of the list.
      const focusIsOutsideList = (event !== null)
        ? !event.currentTarget.contains(event.relatedTarget as Node)
        : true;
      if (focusIsOutsideList && (force === true || !multiple)) {
        handleBlur();
        setIsDisplayed(false);
      }
    },
    [multiple, handleBlur],
  );

  // Finds the direct previous or next option when navigating with keyboard.
  const findSiblingOption = React.useCallback(
    (startIndex: number, direction: number, offset = 1): number => {
      const nextIndex = startIndex + direction * offset;
      if (nextIndex < 0 || nextIndex >= options.length) {
        return startIndex;
      }
      const option = options[nextIndex];
      return (option.type === 'option' && !option.disabled)
        ? nextIndex
        : findSiblingOption(startIndex, direction, offset + 1);
    },
    [options],
  );

  // Automatically triggered when a `focus` event is fired.
  const handleFocus = React.useCallback((optionValue: string, optionIndex: number) => (
    (event: React.FocusEvent<HTMLElement>): void => {
      isFocused.current = true;
      setFocusedOptionIndex(optionIndex);
      if (onFocus !== undefined && onFocus !== null) {
        onFocus(optionValue, event as unknown as FocusEvent);
      }
    }), [onFocus]);

  // Manually triggered, used to simulate `focus` events (`select` mode).
  const focusOption = React.useCallback((optionIndex: number): void => {
    const refNode = (wrapperRef as React.RefObject<HTMLElement>).current;
    if (refNode !== null && optionIndex < refNode.childNodes.length && optionIndex >= 0) {
      (refNode.childNodes[optionIndex] as HTMLElement).focus();
    }
  }, []);

  // Automatically triggered when a `change` event is fired.
  const handleChange = React.useCallback((event: React.ChangeEvent<HTMLInputElement>): void => {
    const selectedIndex = currentValue.indexOf(event.target.value);
    let newValue = [event.target.value];
    if (multiple === true) {
      newValue = (selectedIndex >= 0)
        ? currentValue.slice(0, selectedIndex).concat(currentValue.slice(selectedIndex + 1))
        : currentValue.concat([event.target.value]);
    }
    // If the value hasn't changed, we don't trigger anything.
    if (multiple || newValue[0] !== currentValue[0]) {
      setCurrentValue(newValue);
      if (onChange !== undefined && onChange !== null) {
        onChange((multiple === true) ? newValue : newValue[0], event as unknown as InputEvent);
      }
    }
  }, [onChange, currentValue, multiple]);

  // Manually triggered, used to simulate `change` events (`select` mode).
  const changeOption = React.useCallback((optionIndex: number) => (): void => {
    setFocusedOptionIndex(optionIndex);
    const optionValue = (options[optionIndex] as UIOptionsOption).value;
    handleChange({ target: { value: optionValue } } as React.ChangeEvent<HTMLInputElement>);
    if (select === true) {
      hideList()(null);
    }
  }, [handleChange, hideList, options, select]);

  // -----------------------------------------------------------------------------------------------
  // KEYBOARD NAVIGATION.
  // -----------------------------------------------------------------------------------------------

  // Handles keyboard navigation amongst options.
  const handleKeydown = React.useCallback((event: React.KeyboardEvent<HTMLElement>): void => {
    const { key } = event;
    const navigationControls: Record<string, () => number> = {
      ArrowUp: () => findSiblingOption(focusedOptionIndex, -1),
      ArrowLeft: () => findSiblingOption(focusedOptionIndex, -1),
      ArrowDown: () => findSiblingOption(focusedOptionIndex, +1),
      ArrowRight: () => findSiblingOption(focusedOptionIndex, +1),
      PageUp: () => Math.max(0, findSiblingOption(-1, +1)),
      Home: () => Math.max(0, findSiblingOption(-1, +1)),
      PageDown: () => Math.min(options.length - 1, findSiblingOption(options.length, -1)),
      End: () => Math.min(options.length - 1, findSiblingOption(options.length, -1)),
    };
    const siblingOption = navigationControls[key];
    if (siblingOption !== undefined) {
      // User is navigating through options...
      if (isDisplayed || !select) {
        focusOption(siblingOption());
      } else {
        changeOption(siblingOption())();
      }
      // `event.preventDefault` is not called globally to avoid overriding `Tab` behaviour.
      event.preventDefault();
    } else if (key === ' ' || key === 'Enter') {
      // User wants to select / unselect an option...
      if (isDisplayed === false && select) {
        setIsDisplayed(true);
      } else {
        changeOption(focusedOptionIndex)();
      }
      event.preventDefault();
    } else if (key === 'Escape') {
      // User wants to hide list (`select` mode)...
      hideList(true)(null);
      event.preventDefault();
    }
  }, [
    focusOption,
    findSiblingOption,
    focusedOptionIndex,
    select,
    hideList,
    isDisplayed,
    changeOption,
    options.length,
  ]);

  // -----------------------------------------------------------------------------------------------
  // PROPS REACTIVITY MANAGEMENT.
  // -----------------------------------------------------------------------------------------------

  // Updates current value whenever `value` property changes.
  React.useEffect(() => {
    const newValue = toArray(value);
    setCurrentValue(newValue);
  }, [value]);

  // Updates current value whenever `multiple` property changes.
  React.useEffect(() => {
    setCurrentValue((prevValue) => (
      (multiple || prevValue.length === 0) ? prevValue : [prevValue[0]]));
  }, [multiple]);

  // Updates `firstSelectedOption` ref whenever `currentValue` changes.
  React.useEffect(() => {
    if (currentValue.length === 0) {
      firstSelectedOption.current = findSiblingOption(-1, 1);
    }
    firstSelectedOption.current = Math.max(0, options.findIndex(
      (option) => option.type === 'option' && currentValue.includes(option.value),
    ));
  }, [currentValue, options, findSiblingOption]);

  // Re-focuses the right option whenever `options` property changes, to avoid out of range focus.
  React.useEffect(() => {
    if (isFocused.current) {
      focusOption(firstSelectedOption.current);
    }
  }, [options, focusOption]);

  // HTML elements with `display: none` can't be focused. Thus, we need to wait for the HTML list to
  // be displayed before actually focusing it (`select` mode).
  React.useEffect(() => {
    if (!isDisplayed && buttonRef.current !== null && mounted.current === true) {
      buttonRef.current.focus();
    } else if (isDisplayed && wrapperRef.current !== null) {
      setTimeout(() => {
        focusOption(firstSelectedOption.current);
      }, 10);
    }
  }, [isDisplayed, focusOption]);
  // Prevents focusing the dropdown at component mount in strict mode.
  React.useEffect(() => {
    mounted.current = true;
    return () => { mounted.current = false; };
  }, []);

  // -----------------------------------------------------------------------------------------------
  // COMPONENT RENDERING.
  // -----------------------------------------------------------------------------------------------

  const labelComponent = (label !== undefined) && (
    <label
      className="ui-options__label"
      htmlFor={select ? randomId : `${randomId}_${Math.max(firstSelectedOption.current, 0)}`}
      dangerouslySetInnerHTML={{ __html: markdown(label) }}
    />
  );

  const helperComponent = (helper !== undefined) && (
    <span
      className="ui-options__helper"
      dangerouslySetInnerHTML={{ __html: markdown(helper) }}
    />
  );

  // Display as select list...
  if (select) {
    return (
      <div
        id={id}
        className={className}
      >
        {labelComponent}
        <div className="ui-options__wrapper">
          <button
            name={name}
            type="button"
            id={randomId}
            ref={buttonRef}
            aria-haspopup="listbox"
            onKeyDown={handleKeydown}
            onMouseDown={displayList}
            className="ui-options__wrapper__button"
            aria-labelledby={`${randomId} ${randomId}`}
            tabIndex={(modifiers.includes('disabled') ? -1 : 0)}
            onFocus={handleFocus('', firstSelectedOption.current)}
            dangerouslySetInnerHTML={{ __html: currentValue.map((optionValue) => optionParsedLabels[optionValue]).join(', ') }}
          />
          <ul
            tabIndex={-1}
            role="listbox"
            ref={wrapperRef}
            onBlur={hideList(true)}
            onKeyDown={handleKeydown}
            aria-labelledby={randomId}
            aria-expanded={isDisplayed}
            aria-multiselectable={multiple === true}
            aria-activedescendant={`${randomId}${(focusedOptionIndex)}`}
            className={buildClass('ui-options__wrapper__list', isDisplayed ? `${position} expanded` : position)}
          >
            {options.map((option, index) => {
              const key = `${randomId}${index}`;
              const isOption = option.type === 'option';
              const isDisabled = isOption && option.disabled;
              let optionModifiers = `${option.modifiers ?? ''}${(isDisabled) ? ' disabled' : ''}`;
              const isChecked = isOption && currentValue.includes(option.value);
              if (isChecked) {
                optionModifiers += ' checked';
              }
              let html = '';
              if (isOption) {
                html = optionParsedLabels[option.value];
              } else if (option.type === 'header') {
                html = optionParsedLabels[`header_${index}`];
              }
              return (
                <li
                  id={key}
                  key={key}
                  tabIndex={-1}
                  onBlur={handleBlur}
                  aria-selected={isChecked}
                  dangerouslySetInnerHTML={{ __html: html }}
                  role={isOption ? 'option' : undefined}
                  onMouseDown={(isOption && !isDisabled) ? changeOption(index) : undefined}
                  onFocus={(isOption && !isDisabled) ? handleFocus(option.value, index) : undefined}
                  className={buildClass(`ui-options__wrapper__list__${option.type}`, optionModifiers)}
                />
              );
            })}
          </ul>
        </div>
        {helperComponent}
      </div>
    );
  }

  // Display as radio buttons / checkboxes...
  return (
    <div
      id={id}
      className={className}
    >
      {labelComponent}
      <div
        ref={wrapperRef}
        className="ui-options__wrapper"
      >
        {options.filter((option) => option.type === 'option').map((option, index) => {
          const realOption = option as UIOptionsOption;
          const optionId = `${randomId}_${index}`;
          const isChecked = currentValue.includes(realOption.value);
          let optionModifiers = `${option.modifiers ?? ''}${realOption.disabled ? ' disabled' : ''}`;
          if (isChecked) {
            optionModifiers += ' checked';
          }
          const optionClassName = buildClass('ui-options__wrapper__option', optionModifiers);
          return (
            <label key={realOption.value} className={optionClassName} htmlFor={optionId}>
              <input
                name={name}
                id={optionId}
                onBlur={handleBlur}
                checked={isChecked}
                value={realOption.value}
                onChange={handleChange}
                onKeyDown={handleKeydown}
                disabled={realOption.disabled}
                onFocus={handleFocus(realOption.value, index)}
                className="ui-options__wrapper__option__field"
                type={(multiple === true) ? 'checkbox' : 'radio'}
                tabIndex={(modifiers.includes('disabled') || realOption.disabled || !(((index === 0 || !multiple) && currentValue.length === 0) || realOption.value === currentValue[0]) ? -1 : 0)}
              />
              <span
                className="ui-options__wrapper__option__label"
                dangerouslySetInnerHTML={{ __html: optionParsedLabels[realOption.value] }}
              />
            </label>
          );
        })}
      </div>
      {helperComponent}
    </div>
  );
}

export default React.memo(UIOptions);
