// library/src/scripts/svelte/Textarea.svelte
<!-- Text area. -->
<script lang="ts">
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import markdown from 'scripts/helpers/markdown';
import buildClass from 'scripts/helpers/buildClass';
import generateRandomId from 'scripts/helpers/generateRandomId';

export let value = '';
export let name: string;
export let modifiers = '';
export let readonly = false;
export let autofocus = false;
export let autoresize = false;
export let debounceTimeout = 50;
export let autocomplete: 'on' | 'off' = 'off';
export let id: string | undefined = undefined;
export let cols: number | undefined = undefined;
export let rows: number | undefined = undefined;
export let label: string | undefined = undefined;
export let helper: string | undefined = undefined;
export let maxlength: number | undefined = undefined;
export let placeholder: string | undefined = undefined;
export let onFocus: ((value: string, event: FocusEvent) => void) | undefined = undefined;
export let onBlur: ((value: string, event: FocusEvent) => void) | undefined = undefined;
export let onPaste: ((value: string, event: ClipboardEvent) => void) | undefined = undefined;
export let onChange: ((value: string, event: InputEvent) => void) | undefined = undefined;
export let onKeyDown: ((value: string, event: KeyboardEvent) => void) | undefined = undefined;

let currentValue = value;
let isUserTyping = false;
let timeout: number | null = null;
const randomId = generateRandomId();

$: isDisabled = modifiers.includes('disabled');
$: className = buildClass('ui-textarea', modifiers);

// -------------------------------------------------------------------------------------------------
// CALLBACKS DECLARATION.
// -------------------------------------------------------------------------------------------------

const handleChange = (event: Event): void => {
  clearTimeout(timeout as number);
  isUserTyping = true;
  const newValue = (event.target as HTMLTextAreaElement).value;
  currentValue = newValue;
  // This debounce system prevents triggering `onChange` callback too many times when user is
  // still typing to save performance and make the UI more reactive on low-perfomance devices.
  timeout = setTimeout(() => {
    isUserTyping = false;
    if (onChange !== undefined) {
      onChange(newValue, event as InputEvent);
    }
  }, debounceTimeout) as unknown as number;
};

const handlePaste = (event: ClipboardEvent): void => {
  if (onPaste !== undefined) {
    onPaste(currentValue, event);
  }
};

const handleKeyDown = (event: KeyboardEvent): void => {
  if (onKeyDown !== undefined) {
    onKeyDown(currentValue, event);
  }
};

const handleBlur = (event: FocusEvent): void => {
  if (onBlur !== undefined) {
    onBlur(currentValue, event);
  }
};

const handleFocus = (event: FocusEvent): void => {
  if (onFocus !== undefined) {
    onFocus(currentValue, event);
  }
};

// -------------------------------------------------------------------------------------------------
// PROPS REACTIVITY MANAGEMENT.
// -------------------------------------------------------------------------------------------------

// Updates current value whenever `value` prop changes.
$: {
  // Do not update current value immediatly while user is typing something else.
  if (!isUserTyping) {
    currentValue = value;
  }
}
$: actualRows = (autoresize && rows === undefined) ? Math.max(1, currentValue.split('\n').length) : rows;
</script>

<!-- svelte-ignore a11y-autofocus -->
<div
  id={id}
  class={className}
>
  {#if label !== undefined}
    <label for={randomId} class="ui-textarea__label">
      {@html markdown(label)}
    </label>
  {/if}
  <div class="ui-textarea__wrapper">
    <textarea
      name={name}
      cols={cols}
      id={randomId}
      on:paste={handlePaste}
      rows={actualRows}
      readonly={readonly}
      on:blur={handleBlur}
      value={currentValue}
      maxlength={maxlength}
      autofocus={autofocus}
      disabled={isDisabled}
      on:focus={handleFocus}
      on:keydown={handleKeyDown}
      placeholder={placeholder}
      autocomplete={autocomplete}
      class="ui-textarea__wrapper__field"
      on:input={(readonly !== true && !isDisabled) ? handleChange : undefined}
    />
  </div>
  {#if helper !== undefined}
    <span  class="ui-textarea__helper">
      {@html markdown(helper)}
    </span>
  {/if}
</div>

// library/src/scripts/react/Textarea.tsx
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import * as React from 'react';
import markdown from 'scripts/helpers/markdown';
import PropTypes, { InferProps } from 'prop-types';
import buildClass from 'scripts/helpers/buildClass';
import generateRandomId from 'scripts/helpers/generateRandomId';

const propTypes = {
  id: PropTypes.string,
  cols: PropTypes.number,
  rows: PropTypes.number,
  value: PropTypes.string,
  label: PropTypes.string,
  helper: PropTypes.string,
  onBlur: PropTypes.func,
  onPaste: PropTypes.func,
  onFocus: PropTypes.func,
  onChange: PropTypes.func,
  readonly: PropTypes.bool,
  onKeyDown: PropTypes.func,
  autofocus: PropTypes.bool,
  autoresize: PropTypes.bool,
  maxlength: PropTypes.number,
  modifiers: PropTypes.string,
  placeholder: PropTypes.string,
  autocomplete: PropTypes.string,
  debounceTimeout: PropTypes.number,
  name: PropTypes.string.isRequired,
};

const defaultProps = {
  id: null,
  cols: null,
  rows: null,
  label: null,
  value: null,
  helper: null,
  onBlur: null,
  onFocus: null,
  onPaste: null,
  modifiers: '',
  onChange: null,
  readonly: false,
  maxlength: null,
  onKeyDown: null,
  autofocus: false,
  placeholder: null,
  autoresize: false,
  autocomplete: 'on',
  debounceTimeout: 0,
};

/**
 * Text area.
 */
function UITextarea(props: InferProps<typeof propTypes>): JSX.Element {
  const { name } = props;
  let { autoresize } = props;
  let { id, modifiers, label } = props;
  let { readonly, rows, cols } = props;
  let { helper, onChange, value } = props;
  let { onBlur, maxlength, onPaste } = props;
  let { autofocus, autocomplete, onKeyDown } = props;
  let { onFocus, debounceTimeout, placeholder } = props;

  id = id || null;
  value = value || '';
  cols = cols || null;
  rows = rows || null;
  label = label || null;
  helper = helper || null;
  onBlur = onBlur || null;
  onFocus = onFocus || null;
  onPaste = onPaste || null;
  modifiers = modifiers || '';
  onChange = onChange || null;
  readonly = readonly || false;
  maxlength = maxlength || null;
  onKeyDown = onKeyDown || null;
  autofocus = autofocus || false;
  autoresize = autoresize || false;
  placeholder = placeholder || null;
  autocomplete = autocomplete || 'on';
  debounceTimeout = debounceTimeout ?? 50;

  const isUserTyping = React.useRef(false);
  const [randomId] = React.useState(generateRandomId);
  const timeout = React.useRef<NodeJS.Timeout | null>(null);
  const [currentValue, setCurrentValue] = React.useState(value);
  const isDisabled = (modifiers as string).includes('disabled');
  const className = buildClass('ui-textarea', modifiers as string);
  rows = (autoresize && rows === null) ? Math.max(1, currentValue.split('\n').length) : rows;

  // -----------------------------------------------------------------------------------------------
  // CALLBACKS DECLARATION.
  // -----------------------------------------------------------------------------------------------

  const handleChange = (event: React.ChangeEvent<HTMLTextAreaElement>): void => {
    clearTimeout(timeout.current as NodeJS.Timeout);
    isUserTyping.current = true;
    const newValue = event.target.value;
    setCurrentValue(newValue);
    if (onChange !== null) {
      // This debounce system prevents triggering `onChange` callback too many times when user is
      // still typing to save performance and make the UI more reactive on low-perfomance devices.
      timeout.current = setTimeout(() => {
        isUserTyping.current = false;
        (onChange as JSXElement)(newValue, event);
      }, debounceTimeout as number);
    }
  };

  const handleBlur = (event: React.FocusEvent<HTMLTextAreaElement>): void => {
    if (onBlur !== undefined && onBlur !== null) {
      onBlur(currentValue, event);
    }
  };

  const handleFocus = (event: React.FocusEvent<HTMLTextAreaElement>): void => {
    if (onFocus !== undefined && onFocus !== null) {
      onFocus(currentValue, event);
    }
  };

  // -----------------------------------------------------------------------------------------------
  // PROPS REACTIVITY MANAGEMENT.
  // -----------------------------------------------------------------------------------------------

  // Updates current value whenever `value` prop changes.
  React.useEffect(() => {
    // Do not update current value immediatly while user is typing something else.
    if (!isUserTyping.current) {
      setCurrentValue(value as string);
    }
  }, [value]);

  // -----------------------------------------------------------------------------------------------
  // COMPONENT RENDERING.
  // -----------------------------------------------------------------------------------------------

  return (
    <div
      id={id as string}
      className={className}
    >
      {(label !== null)
        ? <label className="ui-textarea__label" htmlFor={randomId} dangerouslySetInnerHTML={{ __html: markdown(label) }} />
        : null}
      <div className="ui-textarea__wrapper">
        <textarea
          name={name}
          id={randomId}
          onBlur={handleBlur}
          onFocus={handleFocus}
          cols={cols as number}
          rows={rows as number}
          disabled={isDisabled}
          value={currentValue as string}
          readOnly={readonly as boolean}
          maxLength={maxlength as number}
          autoFocus={autofocus as boolean}
          placeholder={placeholder as string}
          autoComplete={autocomplete as string}
          className="ui-textarea__wrapper__field"
          onChange={(readonly === false && !isDisabled) ? handleChange : undefined}
          onPaste={(readonly === false && !isDisabled) ? onPaste as JSXElement : undefined}
          onKeyDown={(readonly === false && !isDisabled) ? onKeyDown as JSXElement : undefined}
        />
      </div>
      {(helper !== null)
        ? <span className="ui-textarea__helper" dangerouslySetInnerHTML={{ __html: markdown(helper) }} />
        : null}
    </div>
  );
}

UITextarea.propTypes = propTypes;
UITextarea.defaultProps = defaultProps;
UITextarea.displayName = 'UITextarea';

export default React.memo(UITextarea);
