// examples/vue/src/scripts/pages/FilePickers.vue
<!-- FileUploaders page. -->

<script lang="ts" setup>
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import { Locale } from 'basx/i18n';

defineProps<{
  locale: Locale;
}>();

const { log } = console;

const onChange = (value: string): void => {
  log('Changed!', value);
};

const onFocus = (): void => {
  log('Focused!');
};
</script>

<template>
  <div className="vgap-5">
    <main className="grid cols-1 hgap-3 vgap-5">
      <a
        href="/"
        className="cols-l-3"
      >GO BACK</a>
      <UIFileUploader name="file-uploader1" />
      <UIFileUploader
        name="file-uploader2"
        label="*ui-file-uploader*"
      />
      <UIFileUploader
        name="file-uploader5"
        label="ui-file-uploader multiple"
        multiple
      />
      <UIFileUploader
        name="file-uploader5"
        label="ui-file-uploader with helper"
        helper="helper"
      />
      <UIFileUploader
        name="file-uploader6"
        label="ui-file-uploader with listener"
        @change="onChange"
      />
      <UIFileUploader
        name="file-uploader11"
        label="ui-file-uploader disabled"
        modifiers="disabled"
      />
      <UIFileUploader
        name="file-uploader12"
        label="ui-file-uploader icon left"
        icon="star"
      />
      <UIFileUploader
        name="file-uploader13"
        label="ui-file-uploader icon right"
        icon="star"
        icon-position="right"
      />
      <UIFileUploader
        name="file-uploader14"
        label="ui-file-uploader with focus listener"
        @focus="onFocus"
      />
      <UIFileUploader
        name="file-uploader15"
        label="ui-file-uploader with accept"
        accept="image/*"
      />
      <UIFileUploader
        name="file-uploader15"
        label="ui-file-uploader with value"
        :value="[new File([], 'test.png')]"
      />
    </main>
  </div>
</template>

// playground/src/scripts/pages/FilePickers.tsx
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import * as React from 'react';
import { UIFilePicker } from 'biuty/react';

const onChange = (value: File[]): void => {
  console.log('Changed!', value); // eslint-disable-line no-console
};

const onFocus = (): void => {
  console.log('Focused!'); // eslint-disable-line no-console
};

/**
 * FileUploaders page.
 */
export default function FileUploaders(): JSX.Element {
  return (
    <div>
      <main className="grid cols-1 hgap-3 vgap-5">
        <a href="/" className="cols-l-3">GO BACK</a>
        <UIFilePicker name="file-uploader1" />
        <UIFilePicker name="file-uploader2" label="*ui-file-uploader*" />
        <UIFilePicker name="file-uploader5" label="ui-file-uploader multiple" multiple />
        <UIFilePicker name="file-uploader5" label="ui-file-uploader with helper" helper="helper" />
        <UIFilePicker name="file-uploader6" label="ui-file-uploader with listener" onChange={onChange} />
        <UIFilePicker name="file-uploader11" label="ui-file-uploader disabled" modifiers="disabled" />
        <UIFilePicker name="file-uploader12" label="ui-file-uploader icon left" icon="star" />
        <UIFilePicker name="file-uploader13" label="ui-file-uploader icon right" icon="star" iconPosition="right" />
        <UIFilePicker name="file-uploader14" label="ui-file-uploader with focus listener" onFocus={onFocus} />
        <UIFilePicker name="file-uploader15" label="ui-file-uploader with accept" accept="image/*" />
        <UIFilePicker name="file-uploader16" label="ui-file-uploader with value" value={[new File([], 'test.png')]} />
      </main>
    </div>
  );
}

FileUploaders.displayName = 'Textfields';
