// library/src/scripts/vue/Button.vue
<template>
  <button
    :id="id"
    :type="type"
    :class="`${className}${(icon !== null && label === null) ? ' ui-button--icon' : ''}`"
    :tabIndex="(modifiers.includes('disabled') ? -1 : 0)"
    @click="clickButton"
    @focus="focusButton"
  >
    <i
      v-if="icon !== null && iconPosition === 'left'"
      class="ui-button__icon"
    >{{ icon }}</i>
    <span
      v-if="(label !== null)"
      class="ui-button__label"
    >{{ label }}</span>
    <i
      v-if="icon !== null && iconPosition === 'right'"
      class="ui-button__icon"
    >{{ icon }}</i>
  </button>
</template>

<script lang="ts">
/**
 * Copyright (c) Matthieu Jabbour. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import Vue from 'vue';
import { Generic } from 'scripts/types';
import buildClass from 'scripts/helpers/buildClass';

interface Props {
  id: string | null;
  modifiers: string;
  icon: string | null;
  label: string | null;
  type: 'button' | 'submit';
  iconPosition: 'left' | 'right';
}

/**
 * Button.
 */
export default Vue.extend<Generic, Generic, Generic, Props>({
  name: 'UIButton',
  props: {
    id: {
      type: String,
      default: null,
      required: false,
    },
    icon: {
      type: String,
      default: null,
      required: false,
    },
    label: {
      type: String,
      default: null,
      required: false,
    },
    type: {
      validator: (value) => value === 'button' || value === 'submit',
      default: 'button',
      required: false,
    },
    modifiers: {
      type: String,
      default: '',
      required: false,
    },
    iconPosition: {
      validator: (value) => value === 'left' || value === 'right',
      default: 'left',
      required: false,
    },
  },
  computed: {
    className(): string {
      return buildClass('ui-button', this.modifiers.split(' '));
    },
  },
  methods: {
    clickButton(): void {
      this.$emit('click');
    },
    focusButton(): void {
      this.$emit('focus');
    },
  },
});
</script>

// library/src/sonar-ui/react/Button.tsx
/**
 * Copyright (c) Matthieu Jabbour. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import * as React from 'react';
import PropTypes, { InferProps } from 'prop-types';
import buildClass from 'sonar-ui/helpers/buildClass';

const propTypes = {
  id: PropTypes.string,
  icon: PropTypes.string,
  label: PropTypes.string,
  onClick: PropTypes.func,
  modifiers: PropTypes.string,
  type: PropTypes.oneOf(['button', 'submit']),
  iconPosition: PropTypes.oneOf(['left', 'right']),
};

const defaultProps = {
  id: null,
  icon: null,
  label: null,
  modifiers: '',
  type: 'button',
  onClick: undefined,
  iconPosition: 'left',
};

/**
 * Button.
 */
export default function UIButton(props: InferProps<typeof propTypes>): JSX.Element {
  // eslint-disable-next-line object-curly-newline
  const { label, icon, iconPosition, onClick, id, modifiers, type } = props;
  const className = buildClass('ui-button', (modifiers as string).split(' '));
  const children = [
    (icon !== null) ? <i key="icon" className="ui-button__icon">{icon}</i> : null,
    (label !== null) ? <span key="label" className="ui-button__label">{label}</span> : null,
  ];
  return (
    <button
      id={id as string}
      onClick={onClick as undefined}
      type={(type === 'submit') ? 'submit' : 'button'}
      className={`${className}${(icon !== null && label === null) ? ' ui-button--icon' : ''}`}
      tabIndex={((modifiers as string).includes('disabled') ? -1 : 0)}
    >
      {(iconPosition === 'left') ? children : children.reverse()}
    </button>
  );
}

UIButton.propTypes = propTypes;
UIButton.defaultProps = defaultProps;
UIButton.displayName = 'UIButton';
