// library/src/scripts/vue/Radio.vue
<template>
  <!-- eslint-disable vue/no-v-html -->
  <div
    :id="id"
    :class="className"
  >
    <label
      v-if="label !== null"
      class="ui-radio__label"
      :for="randomId"
      v-html="markdown(label)"
    />
    <div class="ui-radio__wrapper">
      <label
        v-for="option in options"
        :key="option.value"
        :class="buildClass('ui-radio__wrapper__option', [
          (currentValue === option.value) ? 'checked' : '',
          (option.disabled === true) ? 'disabled' : '',
        ])"
      >
        <input
          v-model="currentValue"
          :name="name"
          type="radio"
          :value="option.value"
          :disabled="option.disabled === true"
          class="ui-radio__wrapper__option__radio"
          :tabindex="(modifiers.includes('disabled') || option.disabled === true) ? -1 : 0"
          @focus="focusField(option.value)"
          @change="changeField"
        >
        <span
          className="ui-radio__wrapper__option__label"
          v-html="markdown(option.label)"
        />
      </label>
    </div>
    <span
      v-if="(helper !== null)"
      className="ui-radio__wrapper__helper"
    >{{ helper }}</span>
  </div>
</template>

<script lang="ts">
/**
 * Copyright (c) Matthieu Jabbour. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import Vue from 'vue';
import { Generic } from 'scripts/types';
import markdown from 'scripts/helpers/markdown';
import buildClass from 'scripts/helpers/buildClass';
import generateRandomId from 'scripts/helpers/generateRandomId';

interface Props {
  name: string;
  id: string | null;
  modifiers: string;
  label: string | null;
  helper: string | null;
  value: string | null;
  options: { value: string; label: string; disabled?: boolean; }[];
}

/**
 * Radio.
 */
export default Vue.extend<Generic, Generic, Generic, Props>({
  name: 'UIRadio',
  props: {
    id: {
      type: String,
      default: null,
      required: false,
    },
    name: {
      type: String,
      default: null,
      required: true,
    },
    label: {
      type: String,
      default: null,
      required: false,
    },
    helper: {
      type: String,
      default: null,
      required: false,
    },
    value: {
      type: String,
      default: null,
      required: false,
    },
    modifiers: {
      type: String,
      default: '',
      required: false,
    },
    options: {
      type: Array,
      required: true,
    },
  },
  data() {
    return {
      currentValue: this.value,
      randomId: generateRandomId(),
    };
  },
  computed: {
    className(): string {
      return buildClass('ui-radio', this.modifiers.split(' '));
    },
  },
  watch: {
    value(): void {
      // Updates current value each time the `value` property is changed.
      this.currentValue = this.value;
    },
  },
  methods: {
    buildClass(base: string, modifiers: string[]): string {
      return buildClass(base, modifiers);
    },
    changeField(): void {
      this.$emit('change', this.currentValue);
    },
    focusField(focusedValue: string): void {
      this.$emit('focus', focusedValue);
    },
    markdown(label: string): string {
      return markdown(label);
    },
  },
});
</script>

// library/src/sonar-ui/react/Radio.tsx
/**
 * Copyright (c) Matthieu Jabbour. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import * as React from 'react';
import PropTypes, { InferProps } from 'prop-types';
import buildClass from 'sonar-ui/helpers/buildClass';
import generateRandomId from 'sonar-ui/helpers/generateRandomId';

const optionType = {
  value: PropTypes.string.isRequired,
  label: PropTypes.string.isRequired,
  disabled: PropTypes.bool,
};

const propTypes = {
  id: PropTypes.string,
  value: PropTypes.string,
  label: PropTypes.string,
  onFocus: PropTypes.func,
  helper: PropTypes.string,
  onChange: PropTypes.func,
  modifiers: PropTypes.string,
  name: PropTypes.string.isRequired,
  options: PropTypes.arrayOf(PropTypes.shape(optionType).isRequired).isRequired,
};

const defaultProps = {
  id: null,
  value: '',
  label: null,
  helper: null,
  onFocus: null,
  modifiers: '',
  onChange: null,
};

/**
 * Radio.
 */
export default function UIRadio(props: InferProps<typeof propTypes>): JSX.Element {
  // eslint-disable-next-line object-curly-newline
  const { id, modifiers, label, helper, value, name, options, onFocus } = props;
  const [randomId] = React.useState(generateRandomId);
  const [currentValue, setCurrentValue] = React.useState(value);
  const className = buildClass('ui-radio', (modifiers as string).split(' '));

  // Updates current value each time the `value` property is changed.
  React.useEffect(() => {
    setCurrentValue(value);
  }, [value]);

  const onChange = (event: React.ChangeEvent<HTMLInputElement>): void => {
    setCurrentValue(event.target.value);
    if (props.onChange !== undefined && props.onChange !== null) {
      props.onChange(event.target.value);
    }
  };

  const focusField = (focusedValue: string) => (): void => {
    if (onFocus !== undefined && onFocus !== null) {
      onFocus(focusedValue);
    }
  };

  return (
    <div
      id={id as string}
      className={className}
    >
      {(label !== null) ? <label className="ui-radio__label" htmlFor={randomId}>{label}</label> : null}
      <div className="ui-radio__wrapper">
        {options.map((option) => {
          const isChecked = currentValue === option.value;
          const isDisabled = option.disabled === true;
          const optionClassName = buildClass('ui-radio__wrapper__option', [isChecked ? 'checked' : '', isDisabled ? 'disabled' : '']);
          return (
            // eslint-disable-next-line jsx-a11y/label-has-associated-control
            <label key={option.value} className={optionClassName}>
              <input
                name={name}
                type="radio"
                checked={isChecked}
                value={option.value}
                readOnly={isDisabled}
                onFocus={focusField(option.value)}
                onChange={isDisabled ? undefined : onChange}
                className="ui-radio__wrapper__option__radio"
              />
              <span className="ui-radio__wrapper__option__label">{option.label}</span>
            </label>
          );
        })}
      </div>
      {(helper !== null) ? <span className="ui-radio__wrapper__helper">{helper}</span> : null}
    </div>
  );
}

UIRadio.propTypes = propTypes;
UIRadio.defaultProps = defaultProps;
UIRadio.displayName = 'UIRadio';
