// library/src/scripts/react/Button.tsx
/**
 * Copyright (c) Matthieu Jabbour. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import * as React from 'react';
import PropTypes, { InferProps } from 'prop-types';

const propTypes = {
  id: PropTypes.string,
  icon: PropTypes.string,
  label: PropTypes.string,
  onClick: PropTypes.func,
  modifiers: PropTypes.string,
};

const defaultProps = {
  id: null,
  icon: null,
  label: null,
  modifiers: 'contained',
  onClick: undefined,
};

/**
 * Button.
 */
export default function UIButton(props: InferProps<typeof propTypes>): JSX.Element {
  // eslint-disable-next-line object-curly-newline
  const { label, icon, onClick, id } = props;
  // eslint-disable-next-line react/destructuring-assignment
  const modifiers = (props.modifiers as string).split(' ');
  const classes = ['ui-button'].concat(modifiers.map((modifier) => `ui-button--${modifier}`));
  return (
    <button
      id={id as string}
      type="button"
      onClick={onClick as undefined}
      className={classes.join(' ')}
      tabIndex={(modifiers.includes('disabled') ? -1 : 0)}
    >
      {(icon !== null) ? <i className="ui-button__icon">{icon}</i> : null}
      {(label !== null) ? <span className="ui-button__label">{label}</span> : null}
    </button>
  );
}

UIButton.propTypes = propTypes;
UIButton.defaultProps = defaultProps;
UIButton.displayName = 'UIButton';

// library/src/scripts/vuejs/Button.vue
<template>
  <button
    :id="id"
    type="button"
    :class="classes.join(' ')"
    :tabIndex="(modifiers.includes('disabled') ? -1 : 0)"
    v-on="(onClick !== undefined) ? { click: onClick } : {}"
  >
    <i
      v-if="icon !== null"
      class="ui-button__icon"
    >{{ icon }}</i>
    <span
      v-if="(label !== null)"
      class="ui-button__label"
    >{{ label }}</span>
  </button>
</template>

<script lang="ts">
/**
 * Copyright (c) Matthieu Jabbour. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import Vue from 'vue';

interface Props {
  id: string | null;
  icon: string | null;
  label: string | null;
  onClick: () => void | undefined;
  modifiers: string;
}

type Generic = Record<string, unknown>;

/**
 * Button.
 */
export default Vue.extend<Generic, Generic, Generic, Props>({
  name: 'UIButton',
  props: {
    id: {
      type: String,
      default: null,
      required: false,
    },
    icon: {
      type: String,
      default: null,
      required: false,
    },
    label: {
      type: String,
      default: null,
      required: false,
    },
    onClick: {
      type: Function,
      default: undefined,
      required: false,
    },
    modifiers: {
      type: String,
      default: 'contained',
      required: false,
    },
  },
  computed: {
    classes(): string[] {
      const modifiers = this.modifiers.split(' ') as string[];
      return ['ui-button'].concat(modifiers.map((modifier) => `ui-button--${modifier}`));
    },
  },
});
</script>
